// SPDX-License-Identifier: Apache-2.0
// Native Muse Home Link. TLS, Noise, credentials and command execution stay on-board.
#include <cstring>
#include <fstream>
#include <iostream>
#include <deque>
#include <map>
#include <sys/stat.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <sys/resource.h>
#include <fcntl.h>
#include <signal.h>
#include "vendor/json.hpp"
#include "openssl_backend.hpp"
#include "gateway_net.hpp"
#include "generative_ui.hpp"
#include "presentation_policy.hpp"
#include "generated_report.hpp"
#include "chat_status.hpp"
#include <xplat/noise/core/ClientSession.h>
using J=nlohmann::json;
using Bytes=std::vector<unsigned char>;
static volatile sig_atomic_t stopping=0;
static std::string state_dir="/mnt/sd/muse/state",ca="/opt/muse-media/ca-certificates.crt";
static double monotime(){timespec ts{};clock_gettime(CLOCK_MONOTONIC,&ts);return ts.tv_sec+ts.tv_nsec/1e9;}
static std::string readfile(const std::string& path,size_t max=1048576){std::ifstream f(path,std::ios::binary);require(bool(f),"file unavailable");std::string data;char buf[4096];while(f.read(buf,sizeof(buf))||f.gcount()){data.append(buf,f.gcount());require(data.size()<=max,"file too large");}return data;}
static void save(const std::string& path,const J& value){std::string temp=path+".new",data=value.dump();int fd=open(temp.c_str(),O_CREAT|O_TRUNC|O_WRONLY|O_CLOEXEC,0600);require(fd>=0,"cannot save state");size_t at=0;while(at<data.size()){ssize_t n=write(fd,data.data()+at,data.size()-at);if(n<=0){close(fd);throw std::runtime_error("cannot write state");}at+=n;}bool ok=fsync(fd)==0;close(fd);require(ok&&rename(temp.c_str(),path.c_str())==0,"cannot commit state");}
static J media(const std::string& action,const J& params=J::object()){
 int fd=socket(AF_INET,SOCK_STREAM|SOCK_CLOEXEC,0);require(fd>=0,"media socket unavailable");timeval timeout{10,0};setsockopt(fd,SOL_SOCKET,SO_RCVTIMEO,&timeout,sizeof(timeout));setsockopt(fd,SOL_SOCKET,SO_SNDTIMEO,&timeout,sizeof(timeout));sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(8765);a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);
 if(connect(fd,(sockaddr*)&a,sizeof(a))){close(fd);throw std::runtime_error("board media service unavailable");}
 std::string body=J({{"action",action},{"params",params}}).dump();std::string data="POST /media HTTP/1.1\r\nHost: localhost\r\nContent-Type: application/json\r\nConnection: close\r\nContent-Length: "+std::to_string(body.size())+"\r\n\r\n"+body;size_t at=0;
 while(at<data.size()){ssize_t n=write(fd,data.data()+at,data.size()-at);if(n<=0){close(fd);throw std::runtime_error("media send failed");}at+=n;}std::string reply;char buf[4096];ssize_t n;while((n=read(fd,buf,sizeof(buf)))>0){reply.append(buf,n);if(reply.size()>1048576){close(fd);throw std::runtime_error("media response too large");}}close(fd);auto header=reply.find("\r\n\r\n");require(header!=std::string::npos,"invalid media response");return J::parse(reply.substr(header+4));
}
static muse_ui::PresentationPolicy presentation_policy;
static pid_t preparation=0,discovery=0;
static double prepare_deadline=0,discovery_started=0;static int prepare_generation=0;static std::string discovery_topic;
static void discover(const std::string& text,bool force=false){if(!presentation_policy.begin(text,std::to_string(time(nullptr))+"-"+std::to_string(getpid())+"-"+std::to_string(monotime()),force))return;save(state_dir+"/visual-lock.json",presentation_policy.state());if(discovery>0){kill(-discovery,SIGTERM);waitpid(discovery,nullptr,0);}if(preparation>0){kill(-preparation,SIGTERM);waitpid(preparation,nullptr,0);preparation=0;}auto r=media("media.progress",{{"operation","begin"},{"topic",text}});discovery_topic=text;discovery_started=monotime();discovery=fork();if(discovery==0){setpgid(0,0);for(int fd=3;fd<1024;fd++)close(fd);execl("/mnt/sd/muse/media/quick-present","quick-present",text.c_str(),presentation_policy.token.c_str(),nullptr);_exit(127);}if(discovery>0)setpgid(discovery,discovery);}
static void poll_workers(){if(discovery>0){int status=0;if(waitpid(discovery,&status,WNOHANG)==discovery){discovery=0;if((!WIFEXITED(status)||WEXITSTATUS(status)!=0)&&!presentation_policy.published){presentation_policy.owned=false;save(state_dir+"/visual-lock.json",presentation_policy.state());}}}if(preparation>0&&waitpid(preparation,nullptr,WNOHANG)==preparation)preparation=0;if(preparation>0&&prepare_deadline>0&&monotime()>prepare_deadline){kill(-preparation,SIGTERM);waitpid(preparation,nullptr,0);preparation=0;auto progress=media("media.progress",{{"operation","status"}});if(progress["payload"]["generation"]==prepare_generation){int i=0;for(const auto& tab:progress["payload"]["tabs"]){if(tab["state"]=="loading"||tab["state"]=="waiting")media("media.progress",{{"operation","update"},{"generation",prepare_generation},{"index",i},{"state",3},{"detail","Presentation deadline: source did not become ready"}});i++;}}}}

static void prepare(int generation,int budget=0){prepare_generation=generation;prepare_deadline=budget>0?monotime()+budget:0;if(preparation>0){kill(-preparation,SIGTERM);waitpid(preparation,nullptr,0);}preparation=fork();if(preparation==0){setpgid(0,0);if(budget>0)setenv("MUSE_FETCH_TIMEOUT","4",1);else unsetenv("MUSE_FETCH_TIMEOUT");setenv("MUSE_MEDIA_BASE","/mnt/sd/muse/media/",1);setenv("MUSE_MEDIA_CACHE_DIR","/mnt/sd/muse/media-cache",1);for(int fd=3;fd<1024;fd++)close(fd);std::string id=std::to_string(generation);execl("/mnt/sd/muse/media/muse-media","muse-media","--prepare",id.c_str(),nullptr);_exit(127);}if(preparation>0)setpgid(preparation,preparation);}
static bool visual_request(std::string text){std::transform(text.begin(),text.end(),text.begin(),[](unsigned char c){return std::tolower(c);});return (text.find("show")!=std::string::npos&&(text.find("stuff")!=std::string::npos||text.find("stats")!=std::string::npos||text.find("news")!=std::string::npos||text.find(" on ")!=std::string::npos||text.find("about")!=std::string::npos))||text.find("wanna see")!=std::string::npos;}
static J present(J params){
 if(params.contains("_board_request"))require(params["_board_request"]==presentation_policy.token,"Request replaced by a newer prompt");muse_ui::presentation_validate(params);static unsigned revision=0;std::string dir="/mnt/sd/muse/media/assets",path=dir+"/genui-report-"+std::to_string(time(nullptr))+"-"+std::to_string(++revision)+".pdf";std::string pdf=muse_ui::report_pdf(params["document"]);{std::ofstream f(path+".new",std::ios::binary);f<<pdf;require(bool(f),"cannot write generated PDF");}require(rename((path+".new").c_str(),path.c_str())==0,"cannot commit generated PDF");params["pdf_url"]=path;auto result=media("media.context",params);if(result.value("ok",false)){result["payload"]["pdf_generated_on_board"]=true;result["payload"]["pdf_path"]=path;prepare(result["payload"].at("generation"),params.value("prepare_seconds",0));if(params.contains("_board_request")&&!params.value("pending_media",false)){presentation_policy.published=true;save(state_dir+"/visual-lock.json",presentation_policy.state());}}return result;
}
static J baseball(const J& params){
 int season=params.value("season",2026),team=params.value("team_id",133);require(season>=1901&&season<=2026&&team>0&&team<1000,"invalid baseball season or team ID");
 std::string path="/api/v1/teams/"+std::to_string(team)+"/stats?stats=season&group=hitting,pitching&season="+std::to_string(season);auto result=https("statsapi.mlb.com",path,"",ca);require(result.status==200,"MLB stats unavailable");J raw=J::parse(result.body),hit,pitch;std::string name;
 for(const auto& group:raw.at("stats"))if(!group.at("splits").empty()){const auto& split=group["splits"][0];name=split.at("team").at("name");if(group.at("group").at("displayName")=="hitting")hit=split.at("stat");else if(group.at("group").at("displayName")=="pitching")pitch=split.at("stat");}
 require(hit.is_object()&&pitch.is_object(),"No MLB season stats for this team");int wins=pitch.at("wins"),losses=pitch.at("losses");
 J doc={{"theme",team==133?"athletics":"vivid"},{"team_id",team},{"title",name+" - "+std::to_string(season)},{"subtitle","MLB regular season | verified from MLB Stats API"},{"source","statsapi.mlb.com | fetched "+std::to_string(time(nullptr))},{"blocks",J::array()}};auto& blocks=doc["blocks"];blocks.push_back({{"type","metrics"},{"items",J::array({{{"title","Record"},{"value",std::to_string(wins)+" - "+std::to_string(losses)}},{{"title","Batting AVG"},{"value",hit.at("avg")}},{{"title","Home runs"},{"value",hit.at("homeRuns")}},{{"title","ERA"},{"value",pitch.at("era")}}})}});
 blocks.push_back({{"type","bar"},{"title","Season record"},{"labels",{"Wins","Losses"}},{"series",J::array({{{"name","Games"},{"values",{wins,losses}}}})}});
 blocks.push_back({{"type","metric"},{"title","Team batting average"},{"value",hit.at("avg")},{"detail","OBP "+hit.at("obp").get<std::string>()+" | SLG "+hit.at("slg").get<std::string>()+" | OPS "+hit.at("ops").get<std::string>()}});
 blocks.push_back({{"type","bar"},{"title","Runs scored vs allowed"},{"labels",{"Scored","Allowed"}},{"series",J::array({{{"name","Runs"},{"values",{hit.at("runs"),pitch.at("runs")}}}})}});
 blocks.push_back({{"type","table"},{"title","Team totals"},{"columns",{"Statistic","Value"}},{"rows",J::array({{"Games",hit.at("gamesPlayed")},{"Home runs",hit.at("homeRuns")},{"Hits",hit.at("hits")},{"Runs batted in",hit.at("rbi")},{"Stolen bases",hit.at("stolenBases")},{"ERA",pitch.at("era")},{"WHIP",pitch.at("whip")},{"Strikeouts",pitch.at("strikeOuts")}})}});
 try{auto leaders=https("statsapi.mlb.com","/api/v1/stats?stats=season&group=hitting&teamId="+std::to_string(team)+"&season="+std::to_string(season)+"&playerPool=ALL&limit=6&sortStat=homeRuns","",ca);if(leaders.status==200){auto splits=J::parse(leaders.body).at("stats")[0].at("splits");J labels=J::array(),values=J::array(),rows=J::array();for(const auto& split:splits){auto who=split.at("player").at("fullName");const auto& stat=split.at("stat");labels.push_back(who);values.push_back(stat.at("homeRuns"));rows.push_back({who,stat.at("avg"),stat.at("homeRuns"),stat.at("rbi")});}if(!labels.empty()){blocks.push_back({{"type","bar"},{"title","Team home run leaders"},{"labels",labels},{"series",J::array({{{"name","HR"},{"values",values}}})}});blocks.push_back({{"type","table"},{"title","Leading hitters"},{"columns",{"Player","AVG","HR","RBI"}},{"rows",rows}});}}}catch(const std::exception&){blocks.push_back({{"type","text"},{"text","Player leaders unavailable; team totals above are verified."}});}
 doc["sources"]=J::array({{{"title","Official MLB team season statistics"},{"url","https://statsapi.mlb.com"+path}}});muse_ui::validate(doc);save(state_dir+"/baseball-stats.json",raw);auto displayed=present({{"version","1"},{"document",doc}});if(displayed.value("ok",false))displayed["payload"].update({{"team",name},{"season",season},{"wins",wins},{"losses",losses},{"source","https://statsapi.mlb.com"}});return displayed;
}
static J execute(const std::string& action,J params){
 try{if(action=="genui.fetch"){discover(params.at("topic"));return {{"ok",true},{"payload",{{"started",true},{"deadline_seconds",60}}}};}if(action=="genui.resume"){auto result=media("media.progress",{{"operation","status"}});prepare(result["payload"].at("generation"),60);return result;}if(action=="genui.prepare"){auto result=media("media.progress",{{"operation","begin"},{"topic","Preparing current presentation"}});prepare(result["payload"].at("generation"));return result;}if(action=="speech.read_text"||action=="speech.stop")return media("media.speech",{{"operation",action=="speech.stop"?"stop":"read"}});if(action=="genui.present"||action=="media.present")return present(params);if(action=="genui.status")return media("media.status");if(action=="genui.capabilities")return {{"ok",true},{"payload",{{"version","1"},{"tabs",{"text","image","pdf","video"}},{"audio_independent",true},{"pdf_generation","on-board"},{"slideshow_max",20}}}};if(action=="sports.baseball")return baseball(params);if(action=="display.picture"||action=="display.image"){params["kind"]="image";if(params.contains("image_url")){params["url"]=params["image_url"];params.erase("image_url");}return media("media.show",params);}
 if(action.rfind("media.",0)==0||action=="audio.tune"||action=="audio.radio"||action=="audio.stations")return media(action,params);
 if(action=="display.controls"){for(auto [name,value]:params.items()){J control;if(name=="volume_percent")control={{"operation","volume"},{"value",value}};else if(name=="muted")control={{"operation","mute"},{"enabled",value}};else if(name=="temperature_f")control={{"operation","temperature"},{"value",value}};else continue;auto result=media("media.control",control);if(!result.value("ok",false))return result;}return media("media.status");}
 if(action=="device.health")return {{"ok",true},{"payload",{{"runtime","board-native"},{"gateway","MA35"},{"transport","direct TLS/Noise"}}}};
 return {{"ok",false},{"error","unsupported board command"}};
 }catch(const std::exception& e){return {{"ok",false},{"error",e.what()}};}
}
struct Session {
 OpenSSLCrypto crypto;nc::ClientSession noise{crypto};WebSocket ws;
 Bytes frame=Bytes(262144),envelope=Bytes(262144),wire=Bytes(nc::ClientSession::kMaxOutboundWebSocketPayloadSize),plain=Bytes(65536),response=Bytes(1048576);
 std::array<nc::HeaderView,64> headers{};std::string control,chat;int64_t next_id=3;bool registered=false;
 bool require_presentation=false;
 muse_chat::Status chat_status;std::map<int64_t,std::string> request_replies;std::map<int64_t,int> request_codes;
 std::string node;std::map<std::string,std::string> messages;std::deque<std::pair<std::string,std::string>> seen;
 std::map<std::string,double> displayed;std::deque<std::string> speech;pid_t tts=0;bool manual_speech=false;double speech_poll=0;std::string register_id="board-register";
 Session(const std::string& host,const std::string& vm,const std::string& token,const std::string& id):ws(host,vm,token,ca),node(id){
  try{chat_status.value=J::parse(readfile(state_dir+"/chat-status.json"));require_presentation=chat_status.value.value("presentation_required",false);}catch(...){}
  auto first=noise.WriteHandshakeMessage1({wire.data(),wire.size()});require(first.ok(),"Noise message 1 failed");ws.send(wire.data(),first.size());auto second=ws.receive();size_t extra=0;require(noise.ReadHandshakeMessage2({second.data(),second.size()},{plain.data(),plain.size()},extra).ok(),"Noise message 2 failed");auto third=noise.WriteHandshakeMessage3({},{wire.data(),wire.size()});if(!third.ok())throw std::runtime_error(std::string("Noise message 3 failed: ")+third.status().str()+" capacity="+std::to_string(wire.size()));ws.send(wire.data(),third.size());std::cerr<<"Noise session established on MA35\n";
 }
 ~Session(){if(tts>0){kill(-tts,SIGKILL);waitpid(tts,nullptr,0);}if(manual_speech)try{media("media.speech",{{"operation","state"},{"phase",0}});}catch(...){}}
 void flush(){while(noise.HasOutboundWebSocketPayload()){auto result=noise.WriteNextOutboundWebSocketPayload({wire.data(),wire.size()});require(result.ok(),"Noise encryption failed");ws.send(wire.data(),result.size());}}
 void request(int64_t id,const std::string& path,const std::string& body,bool end=true){
  nc::HeaderView hs[]={{"Content-Type","application/json"},{"x-app-id","musegadget"},{"Accept",path=="/chat/stream"?"application/json":"application/x-ndjson"}};
  nc::ApplicationRequestView req{"POST",path,{hs,3},{reinterpret_cast<const unsigned char*>(body.data()),body.size()},end};
  require(noise.StartOutboundApplicationRequest(nc::ServiceType::Daemon,id,req,{frame.data(),frame.size()},{envelope.data(),envelope.size()}).ok(),"Noise request failed");flush();
 }
 void chunk(int64_t id,const std::string& body,bool end=false){require(noise.StartOutboundBodyChunk(nc::ServiceType::Daemon,id,{{reinterpret_cast<const unsigned char*>(body.data()),body.size()},end},{frame.data(),frame.size()},{envelope.data(),envelope.size()}).ok(),"Noise chunk failed");flush();}
 void send(J value){auto text=value.dump();uint32_t size=text.size();std::string body(4,'\0');for(int i=0;i<4;i++)body[i]=size>>(8*i);body+=text;chunk(1,body);}
 void open(const J& specs){request(1,"/link-control","",false);send({{"type","req"},{"id",register_id},{"method","link.register"},{"params",{{"node_id",node},{"display_name","MA35H0 board"},{"platform","linux"},{"version","0.1.0"},{"device_family","homehub"},{"model_id","linux"},{"is_wakeup_supported",false},{"commands_v2",specs}}}});request(2,"/chat/subscribe","{}");}
 void command(J msg){
  if(msg.value("id",std::string())==register_id&&!msg.contains("method")){require(!msg.contains("error")||msg["error"].is_null(),"Muse registration rejected");registered=true;if(!presentation_policy.published)media("media.progress",{{"operation","activity"},{"detail","Muse connected; API registered"}});std::cerr<<"registered with the Muse on MA35\n";save(state_dir+"/status.json",{{"connected",true},{"registered",true},{"runtime","board-native"},{"node_id",node}});return;}
  std::string ev=msg.value("event",std::string());if(ev=="link.unpaired"||ev=="node.unpaired"){rename((state_dir+"/pairing.json").c_str(),(state_dir+"/pairing.revoked.json").c_str());throw std::runtime_error("Muse removed this device");}
  if(msg.value("method",std::string())=="link.invoke"&&msg.contains("id")){std::string name=msg.value("command",std::string());J result;if(presentation_policy.retain(name,msg.value("params",J::object()))){result={{"ok",true},{"payload",{{"preserved",true},{"accepted",false},{"reason","The first board presentation is retained. Late Muse visual updates are disabled; a new user prompt starts a new topic."}}}};}else {if(name!="genui.status")media("media.progress",{{"operation","activity"},{"detail","Board API: "+name}});if(require_presentation&&(name=="display.picture"||name=="display.image"||name=="media.show"||name=="media.ui"))result={{"ok",false},{"error","Use genui.present immediately with a sourced document and pending_media=true so Text/PDF appear before image/video research completes. Send later genui.present updates with the SAME document/title plus real media URLs. The board downloads and validates media; do not download photo bytes on Muse or wait for all sources before publishing."}};else result=execute(name,msg.value("params",J::object()));}if((name=="genui.present"||name=="media.present")&&result.value("ok",false)){require_presentation=false;chat_status.value["presentation_required"]=false;save(state_dir+"/chat-status.json",chat_status.value);}result["method"]="link.result";result["id"]=msg["id"];send(result);std::cerr<<"invoke "<<name<<" "<<(result.value("ok",false)?"ok":"failed")<<" on MA35\n";}
 }
 void event(J row){
  if(!row.is_object()||row.value("type",std::string())!="event")return;J fields=row;if(row.contains("payload")&&row["payload"].is_object())fields.update(row["payload"]);
  if(chat_status.event(fields)){save(state_dir+"/chat-status.json",chat_status.value);std::string activity=fields.value("activity_text",std::string());if(!activity.empty()){auto progress=media("media.progress",{{"operation","status"}});bool awaiting=false;for(const auto& tab:progress["payload"]["tabs"])if(tab["kind"]=="text"&&tab["state"]=="waiting")awaiting=true;if(awaiting)media("media.progress",{{"operation","activity"},{"detail","Muse: "+activity}});}}
  std::string event=fields.value("event_name",fields.value("event",std::string()));std::string mid=fields.value("message_id",fields.value("id",std::string()));std::string text;
  for(auto key:{"display_text","content","text"})if(fields.contains(key)&&fields[key].is_string()){text=fields[key];break;}
  if(mid.empty()||event.rfind("delta.",0)!=0&&event!="message.assistant"&&event!="message.user")return;
  if(fields.contains("seq")){std::pair<std::string,std::string> key{mid,event+fields["seq"].dump()};if(std::find(seen.begin(),seen.end(),key)!=seen.end())return;seen.push_back(key);if(seen.size()>2048)seen.pop_front();}
  if(event=="delta.text_append")messages[mid]+=text;else if(!text.empty()&&event!="delta.presentation")messages[mid]=text;
  if(event=="message.user"&&visual_request(text)){auto current=media("media.progress",{{"operation","status"}});if(!current["payload"].value("visible",false)||current["payload"].value("topic",std::string())!=text){require_presentation=true;discover(text);}}
  if(messages.size()>60)messages.erase(messages.begin());auto content=messages[mid];if(content.size()>262000)content.resize(262000);
  bool completed=event=="delta.message_done"||event=="message.assistant"||event=="message.user";
  if(completed&&event!="message.user"&&!content.empty()){chat_status.value["last_assistant_text"]=content.substr(0,4000);save(state_dir+"/chat-status.json",chat_status.value);}
  if(!presentation_policy.owned&&!content.empty()&&(completed||monotime()-displayed[mid]>.25)){
   displayed[mid]=monotime();J params={{"kind","text"},{"text",content},{"caption",event=="message.user"?"You":"Muse"}};
   auto ui=muse_ui::from_text(content);if(!ui.is_null())params["ui"]=ui;
   if(event=="delta.presentation")for(const char* key:{"ui","document"})if(fields.contains(key)&&fields[key].is_object()){try{muse_ui::validate(fields[key]);params["ui"]=fields[key];}catch(...){} }
   auto result=media("media.remember",params);if(!result.value("ok",false))std::cerr<<"text cache update failed\n";
   auto current=media("media.status");if(current["payload"].value("media_kind",std::string("none"))=="none")media("media.switch",{{"kind","text"}});
   if(completed&&event!="message.user"&&speech.size()<16&&std::find(spoken.begin(),spoken.end(),mid)==spoken.end()){speech.push_back(content.substr(0,1800));spoken.push_back(mid);if(spoken.size()>128)spoken.pop_front();}
  }
 }
 std::deque<std::string> spoken;
 void cancel_speech(){speech.clear();if(tts>0){kill(-tts,SIGKILL);while(waitpid(tts,nullptr,0)<0&&errno==EINTR){}tts=0;}manual_speech=false;}
 void speak(){
  if(monotime()-speech_poll<.2)return;speech_poll=monotime();auto control=media("media.speech",{{"operation","poll"}});int operation=control["payload"].value("request",0);
  if(operation){cancel_speech();if(operation==1){manual_speech=true;speech.push_back(control["payload"].value("text",std::string()));}else media("media.speech",{{"operation","state"},{"phase",0}});}
  auto playback=media("media.status");if(playback["payload"].value("audio_running",false)){if(tts>0||!speech.empty())cancel_speech();return;}
  if(tts>0){int result=0;if(waitpid(tts,&result,WNOHANG)==tts){tts=0;if(manual_speech){bool ok=WIFEXITED(result)&&WEXITSTATUS(result)==0;media("media.speech",{{"operation","state"},{"phase",ok?0:3},{"error",ok?"":"Speech playback failed; see board speech log"}});manual_speech=false;}}else if(manual_speech){try{auto state=readfile("/mnt/sd/muse/tts/read-status.txt",64);if(state.find("playing")!=std::string::npos)media("media.speech",{{"operation","state"},{"phase",2}});}catch(...){} }}
  if(tts||speech.empty()||access("/mnt/sd/muse/tts/speak",X_OK))return;auto status=media("media.status");if(status["payload"].value("audio_running",false))return;
  auto text=speech.front();speech.pop_front();std::string path="/mnt/sd/muse/tts/input.txt";{std::ofstream file(path);file<<text<<"\n";if(!file){if(manual_speech)media("media.speech",{{"operation","state"},{"phase",3},{"error","Cannot prepare speech input"}});manual_speech=false;return;}}chmod(path.c_str(),0600);if(manual_speech){std::ofstream file("/mnt/sd/muse/tts/read-status.txt");file<<"preparing";}
  tts=fork();if(tts==0){setpgid(0,0);setpriority(PRIO_PROCESS,0,10);int input=::open(path.c_str(),O_RDONLY);dup2(input,0);close(input);if(manual_speech){setenv("MUSE_TTS_STATUS_FILE","/mnt/sd/muse/tts/read-status.txt",1);setenv("MUSE_TTS_ENGINE","espeak",1);}else unsetenv("MUSE_TTS_STATUS_FILE");for(int fd=3;fd<1024;fd++)close(fd);execl("/mnt/sd/muse/tts/speak","speak",nullptr);_exit(127);}if(tts>0)setpgid(tts,tts);else if(tts<0){tts=0;if(manual_speech)media("media.speech",{{"operation","state"},{"phase",3},{"error","Cannot start speech process"}});manual_speech=false;}
 }

 void receive(){auto data=ws.receive();if(data.empty())return;auto result=noise.ProcessInboundWebSocketPayload({data.data(),data.size()},{plain.data(),plain.size()},{response.data(),response.size()},{headers.data(),headers.size()});require(result.ok(),"Noise inbound frame rejected");if(result.frame_status!=nc::InboundFrameStatus::Complete)return;
  auto& f=result.frame;require(f.kind!=nc::ServiceFrameKind::Reset,"Muse stream reset");nc::ConstByteSpan bytes=f.kind==nc::ServiceFrameKind::Response?f.response.body:f.body_chunk.data;bool end=f.kind==nc::ServiceFrameKind::Response?f.response.end_body:f.body_chunk.end_body;
  if(f.stream_id<3&&f.kind==nc::ServiceFrameKind::Response&&f.response.status>=400)throw std::runtime_error("Muse request refused: "+std::to_string(f.response.status));
  if(f.stream_id==1){control.append(reinterpret_cast<const char*>(bytes.data()),bytes.size());require(control.size()<=1048576,"control buffer too large");while(control.size()>=4){uint32_t len=0;for(int i=0;i<4;i++)len|=uint32_t(static_cast<unsigned char>(control[i]))<<(8*i);require(len<=262144,"control message too large");if(control.size()<len+4)break;auto text=control.substr(4,len);control.erase(0,len+4);if(len)command(J::parse(text));}require(!end,"control stream ended");}
  else if(f.stream_id==2){chat.append(reinterpret_cast<const char*>(bytes.data()),bytes.size());require(chat.size()<=1048576,"chat event too large");size_t pos;while((pos=chat.find('\n'))!=std::string::npos){auto line=chat.substr(0,pos);chat.erase(0,pos+1);try{event(J::parse(line));}catch(const std::exception&){std::cerr<<"chat event skipped\n";}}if(end){chat.clear();request(2,"/chat/subscribe","{}");}}
  else if(request_replies.count(f.stream_id)){auto& reply=request_replies[f.stream_id];if(f.kind==nc::ServiceFrameKind::Response)request_codes[f.stream_id]=f.response.status;reply.append(reinterpret_cast<const char*>(bytes.data()),bytes.size());require(reply.size()<=262144,"chat acknowledgement too large");chat_status.response(f.stream_id,request_codes[f.stream_id],reply,end);if(end){media("media.progress",{{"operation","activity"},{"detail",request_codes[f.stream_id]>=400?"Muse rejected request (HTTP "+std::to_string(request_codes[f.stream_id])+")":"Muse acknowledged request (HTTP "+std::to_string(request_codes[f.stream_id])+")"}});save(state_dir+"/chat-status.json",chat_status.value);request_replies.erase(f.stream_id);request_codes.erase(f.stream_id);}}
 }
};
static int local_server(){int fd=socket(AF_UNIX,SOCK_STREAM|SOCK_CLOEXEC,0);require(fd>=0,"local socket unavailable");sockaddr_un a{};a.sun_family=AF_UNIX;strcpy(a.sun_path,"/run/musegadget.sock");unlink(a.sun_path);require(bind(fd,(sockaddr*)&a,sizeof(a))==0&&listen(fd,8)==0,"cannot open board local API");chmod(a.sun_path,0600);return fd;}
static void local(int server,Session* session){int c=accept4(server,nullptr,nullptr,SOCK_CLOEXEC);if(c<0)return;timeval timeout{2,0};setsockopt(c,SOL_SOCKET,SO_RCVTIMEO,&timeout,sizeof(timeout));setsockopt(c,SOL_SOCKET,SO_SNDTIMEO,&timeout,sizeof(timeout));std::string line;char buf[4096];J result;try{while(line.find('\n')==std::string::npos){ssize_t n=read(c,buf,sizeof(buf));require(n>0,"incomplete local request");line.append(buf,n);require(line.size()<65536,"local request too large");}J q=J::parse(line.substr(0,line.find('\n')));auto action=q.value("action",std::string());if(action=="status")result={{"ok",true},{"payload",{{"connected",session!=nullptr},{"registered",session&&session->registered},{"runtime","board-native"}}}};
  else if(action=="chat.status"){result={{"ok",true},{"payload",session?session->chat_status.value:J::object()}};}
  else if(q.contains("message")){require(session&&session->registered,"not connected to Muse");J body={{"message",q["message"]},{"device_id",session->node},{"output_modality","text"}};if(q.contains("session_id"))body["session_id"]=q["session_id"];auto id=session->next_id++;session->chat_status.submitted(id,q.at("message"));session->require_presentation=q.value("genui",false)||visual_request(q.at("message"));if(session->require_presentation)discover(q.at("message"),true);session->chat_status.value["presentation_required"]=session->require_presentation;session->request_replies[id]="";session->request_codes[id]=0;save(state_dir+"/chat-status.json",session->chat_status.value);session->request(id,"/chat/stream",body.dump());result={{"ok",true},{"payload",{{"submitted",true},{"stream_id",id}}}};}
  else if(action=="speech.stop"){require(session,"not connected");session->cancel_speech();result=media("media.speech",{{"operation","stop"}});}
  else result=execute(action,q.value("params",J::object()));
 }catch(const std::exception& e){result={{"ok",false},{"error",e.what()}};}auto out=result.dump()+"\n";size_t at=0;while(at<out.size()){ssize_t n=write(c,out.data()+at,out.size()-at);if(n<=0)break;at+=n;}close(c);}
int main(int argc,char** argv){signal(SIGPIPE,SIG_IGN);signal(SIGTERM,[](int){stopping=1;});signal(SIGINT,[](int){stopping=1;});if(argc>1)state_dir=argv[1];if(getenv("MUSE_CA_FILE"))ca=getenv("MUSE_CA_FILE");
 try{if(argc>2&&std::string(argv[1])=="--local"){int fd=socket(AF_UNIX,SOCK_STREAM,0);sockaddr_un a{};a.sun_family=AF_UNIX;strcpy(a.sun_path,"/run/musegadget.sock");require(connect(fd,(sockaddr*)&a,sizeof(a))==0,"board gateway unavailable");std::string q=std::string(argv[2])+"\n";require(write(fd,q.data(),q.size())==ssize_t(q.size()),"local send failed");char buf[4096];ssize_t n;while((n=read(fd,buf,sizeof(buf)))>0)std::cout.write(buf,n);close(fd);return 0;}try{presentation_policy.restore(J::parse(readfile(state_dir+"/visual-lock.json")));}catch(...){}int server=local_server();int backoff=2;while(!stopping){try{
  J pairing=J::parse(readfile(state_dir+"/pairing.json"));J identity=J::parse(readfile(state_dir+"/identity.json"));auto mac=identity["mac"].get<std::string>();mac.erase(std::remove(mac.begin(),mac.end(),':'),mac.end());std::string node="homelink-"+mac.substr(mac.size()-6);std::string root=pairing.value("api_url_v2",std::string("https://api.muse.ai"));if(root.empty())root="https://api.muse.ai";require(root.rfind("https://",0)==0,"HTTPS API required");auto host=root.substr(8);while(!host.empty()&&host.back()=='/')host.pop_back();require(host.find('/')==std::string::npos,"unsupported API base path");
  bool force=false;HTTPReply vms{0,{}};
  for(int attempt=0;attempt<2;attempt++){
   if(force||time(nullptr)-pairing.value("access_token_saved_at",int64_t(0))>=3*3600){std::string refresh=pairing["refresh_token"];refresh="hatch_refresh:"+refresh.substr(refresh.rfind(':')==std::string::npos?0:refresh.rfind(':')+1);J body={{"device_id",node}};try{auto sdk=readfile(state_dir+"/sdk_token",1024);while(!sdk.empty()&&isspace(sdk.back()))sdk.pop_back();body["sdk_token"]=sdk;}catch(...){}auto r=https(host,"/device_token/refresh",refresh,ca,body.dump(),"POST");if(r.status==401){rename((state_dir+"/pairing.json").c_str(),(state_dir+"/pairing.revoked.json").c_str());throw std::runtime_error("pairing revoked");}require(r.status==200,"token refresh failed");J tokens=J::parse(r.body);if(tokens.contains("payload"))tokens=tokens["payload"];require(tokens.contains("access_token")&&tokens.contains("refresh_token"),"invalid refresh response");pairing["access_token"]=tokens["access_token"];pairing["refresh_token"]=tokens["refresh_token"];pairing["access_token_saved_at"]=time(nullptr);save(state_dir+"/pairing.json",pairing);std::cerr<<"device token rotated on MA35\n";}
   vms=https(host,"/fetch_vms",pairing["access_token"],ca);if(vms.status!=401)break;force=true;
  }
  require(vms.status==200,"VM lookup failed");auto list=J::parse(vms.body).at("vm_list");require(list.is_array()&&!list.empty(),"no Muse VM available");J vm=list[0];for(auto& item:list)if(item.value("default",false)){vm=item;break;}auto specs=J::parse(readfile(state_dir+"/commands.json"));Session session(pairing.value("noise_host",std::string("hatch.metaaivm.com")),vm.value("vm_id",vm.value("vm_name",std::string())),vm.at("vm_auth_token"),node);session.open(specs);double ping=monotime(),last_rx=ping;
  while(!stopping){poll_workers();pollfd p{server,POLLIN,0};if(poll(&p,1,0)>0)local(server,&session);if(session.ws.tls.ready(50)){session.receive();last_rx=monotime();}session.speak();if(monotime()-ping>20){session.ws.send(nullptr,0,9);ping=monotime();}require(monotime()-last_rx<90,"Muse connection idle timeout");if(session.registered)backoff=2;}
 }catch(const std::exception& e){std::cerr<<"gateway reconnect: "<<e.what()<<"\n";try{media("media.progress",{{"operation","activity"},{"detail","Muse connection retry in "+std::to_string(backoff)+"s: "+e.what()}});}catch(...){}save(state_dir+"/status.json",{{"connected",false},{"registered",false},{"runtime","board-native"},{"error",e.what()}});for(int i=0;i<backoff*10&&!stopping;i++){poll_workers();pollfd p{server,POLLIN,0};if(poll(&p,1,100)>0)local(server,nullptr);}backoff=std::min(60,backoff*2);}}
 close(server);unlink("/run/musegadget.sock");return 0;
 }catch(const std::exception& e){std::cerr<<e.what()<<"\n";return 1;}
}
