// SPDX-License-Identifier: Apache-2.0
#pragma once
#include "generative_ui.hpp"
#include <sstream>
#include <vector>
#include <iomanip>
namespace muse_ui {
inline std::string pdf_escape(const std::string& text){std::string out;for(unsigned char c:text){if(c=='('||c==')'||c=='\\')out+='\\';if(c>=32&&c<127)out+=c;else if(c=='\n')out+=' ';}return out;}
// A bounded, board-native PDF writer: no browser, Python or external PDF service.
inline std::string report_pdf(const J& doc){
 validate(doc);std::vector<std::string> pages;std::ostringstream stream;double y=665;
 auto text=[&](const std::string& value,double x,double yy,int size=12,bool bold=false){stream<<"BT /"<<(bold?"F2":"F1")<<" "<<size<<" Tf "<<x<<" "<<yy<<" Td ("<<pdf_escape(value)<<") Tj ET\n";};
 auto header=[&](){stream<<"0.02 0.27 0.20 rg 0 700 612 92 re f\n0.98 0.78 0.17 rg 0 695 612 5 re f\n1 1 1 rg\n";text(doc.value("title",std::string("Muse report")),36,748,23,true);text(doc.value("subtitle",std::string("Generated by Muse GenUI on board")),36,720,10);stream<<"0.08 0.13 0.18 rg\n";};
 auto finish=[&](){stream<<"0.35 0.43 0.50 rg\n";text("Muse GenUI | generated on MA35 | "+std::to_string(pages.size()+1),36,24,9);pages.push_back(stream.str());stream.str("");stream.clear();y=665;};
 auto room=[&](double h){if(y-h<55){finish();header();}};
 auto paragraph=[&](std::string value){while(!value.empty()){room(18);size_t n=std::min(size_t(88),value.size());auto nl=value.find('\n');if(nl<n)n=nl;else if(n<value.size()){auto space=value.rfind(' ',n);if(space!=std::string::npos&&space>30)n=space;}text(value.substr(0,n),40,y,11);y-=16;value.erase(0,n);while(!value.empty()&&(value[0]==' '||value[0]=='\n'))value.erase(0,1);}};
 header();
 for(const auto& block:doc["blocks"]){auto type=block.value("type",std::string());room(70);stream<<"0.02 0.35 0.26 rg\n";text(block.value("title",block.value("label",std::string())),36,y,15,true);stream<<"0.08 0.13 0.18 rg\n";y-=25;
  if(type=="metric"){text(display(block["value"])+" "+block.value("unit",std::string()),40,y,24,true);y-=30;paragraph(block.value("detail",std::string()));}
  else if(type=="metrics"){for(const auto& item:block["items"]){paragraph(item.value("title",std::string())+": "+display(item["value"])+" "+item.value("unit",std::string()));}}
  else if(type=="text")paragraph(block.value("text",std::string()));
  else if(type=="progress")paragraph(display(block["value"])+" / "+display(block.value("max",J(100)))+" "+block.value("unit",std::string()));
  else if(type=="table"){std::string columns;for(const auto& col:block["columns"])columns+=col.get<std::string>()+"   |   ";paragraph(columns);for(const auto& row:block["rows"]){std::string cells;for(const auto& cell:row)cells+=display(cell)+"   |   ";paragraph(cells);}}
  else {for(const auto& series:block["series"]){room(35);text(series.value("name",std::string("Series")),40,y,12,true);y-=20;double peak=1;for(const auto& v:series["values"])peak=std::max(peak,std::abs(v.get<double>()));for(size_t i=0;i<block["labels"].size();i++){room(22);double value=series["values"][i].get<double>();stream<<"0.90 0.94 0.93 rg 190 "<<y-3<<" 290 14 re f\n0.02 0.52 0.37 rg 190 "<<y-3<<" "<<290*std::abs(value)/peak<<" 14 re f\n0.08 0.13 0.18 rg\n";text(block["labels"][i].get<std::string>().substr(0,22),40,y,10);text(display(series["values"][i]),490,y,10);y-=22;}}}
  y-=15;
 }
 room(55);text("Sources",36,y,15,true);y-=24;paragraph(doc.value("source",std::string("Sources supplied by Muse.")));if(doc.contains("sources"))for(const auto& source:doc["sources"])paragraph(source.value("title",std::string())+" "+source.value("url",std::string()));finish();
 std::vector<std::string> objects(4+pages.size()*2);objects[0]="<< /Type /Catalog /Pages 2 0 R >>";std::string kids;for(size_t i=0;i<pages.size();i++)kids+=std::to_string(5+2*i)+" 0 R ";objects[1]="<< /Type /Pages /Count "+std::to_string(pages.size())+" /Kids [ "+kids+"] >>";objects[2]="<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>";objects[3]="<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>";
 for(size_t i=0;i<pages.size();i++){objects[4+2*i]="<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents "+std::to_string(6+2*i)+" 0 R >>";objects[5+2*i]="<< /Length "+std::to_string(pages[i].size())+" >>\nstream\n"+pages[i]+"endstream";}
 std::ostringstream out;out<<"%PDF-1.4\n";std::vector<size_t> offsets;for(size_t i=0;i<objects.size();i++){offsets.push_back(size_t(out.tellp()));out<<i+1<<" 0 obj\n"<<objects[i]<<"\nendobj\n";}auto xref=size_t(out.tellp());out<<"xref\n0 "<<objects.size()+1<<"\n0000000000 65535 f \n";for(auto offset:offsets)out<<std::setw(10)<<std::setfill('0')<<offset<<" 00000 n \n";out<<"trailer\n<< /Size "<<objects.size()+1<<" /Root 1 0 R >>\nstartxref\n"<<xref<<"\n%%EOF\n";return out.str();
}
}
