// SPDX-License-Identifier: Apache-2.0
// Board-native, bounded media renderer. No gateway process is used at runtime.
#include "vendor/json.hpp"
#include "audio_eq.hpp"
#include "codec_dsp.hpp"
#include <sys/syscall.h>
#define STB_IMAGE_IMPLEMENTATION
#define STBI_MAX_DIMENSIONS 8192
#include "vendor/stb_image.h"
#define STB_TRUETYPE_IMPLEMENTATION
#include "vendor/stb_truetype.h"
#include <linux/fb.h>
#include <linux/input.h>
#include <linux/videodev2.h>
#include <sys/socket.h>
#include <sys/mman.h>
#include <sys/wait.h>
#include <sys/ioctl.h>
#include <sys/resource.h>
#include <netinet/in.h>
#include <poll.h>
#include <fcntl.h>
#include <unistd.h>
#include <signal.h>
#include <cmath>
#include <fstream>
#include <iostream>
#include <chrono>
#include <algorithm>
#include <deque>
#include <thread>
#include <mutex>
#include <condition_variable>
using J=nlohmann::json;
static const std::string base="/opt/muse-media/";
struct Shared {float zoom=1,panx=0,pany=0;int full=0,page=1,version=0,frames=0,paused=0,temperature=72,volume=75,muted=0,decoder_pid=0,audio_pid=0,audio_decoder_pid=0,eq_view=1,eq_version=0;int eq_gain[10]{},eq_level[10]{},hw_gain[5]{},sw_eq=1,hw_eq=0,limiter=0,mic_hpf=1,mic_alc=0,mic_gate=0,codec_available=0,spectrum_version=0,audio_running=0,audio_blocks=0;char state[24]="idle",error[160]="";};
static muse_audio::Codec* codec=nullptr;static Shared *s;static pid_t worker=0;static J current;static std::deque<J> pending;static std::string fbpath="/dev/fb0";
static double now(){return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();}
static void state(const char *v){snprintf(s->state,sizeof(s->state),"%s",v);}
static bool exists(std::string p){return access(p.c_str(),X_OK)==0;}
static std::string readfile(std::string p,size_t limit){std::ifstream f(p,std::ios::binary);std::string v;char b[4096];while(f.read(b,sizeof(b))||f.gcount()){v.append(b,f.gcount());if(v.size()>limit)throw std::runtime_error("media exceeds size limit");}if(!f.eof())throw std::runtime_error("cannot read media");return v;}
static pid_t spawn(const std::vector<std::string>&args,int input=-1,int output=-1,int extra=-1,bool capture_error=false){pid_t p=fork();if(p==0){if(input>=0)dup2(input,0);else{int fd=open("/dev/null",O_RDONLY);dup2(fd,0);}if(output>=0)dup2(output,1);else{int fd=open("/dev/null",O_WRONLY);dup2(fd,1);}int fd=open(args[0]=="/usr/bin/aplay"?"/tmp/muse-media-audio.log":"/tmp/muse-media-backend.log",O_CREAT|O_WRONLY|O_TRUNC,0600);dup2(capture_error&&output>=0?output:fd,2);if(extra>=0)dup2(extra,3);for(int i=extra>=0?4:3;i<1024;i++)close(i);std::vector<char*> av;for(auto&a:args)av.push_back(const_cast<char*>(a.c_str()));av.push_back(nullptr);execv(av[0],av.data());_exit(127);}if(p<0)throw std::runtime_error("cannot start backend");return p;}
static void waitok(pid_t p){int st=0;while(waitpid(p,&st,0)<0&&errno==EINTR){}if(!WIFEXITED(st)||WEXITSTATUS(st))throw std::runtime_error("media backend failed; see board backend log");}
static std::string fetch(std::string u){if(u.rfind("/opt/muse-media/assets/",0)==0)return u;if(u.rfind("https://",0)!=0)throw std::runtime_error("source must be HTTPS or a board asset path");waitok(spawn({base+"curl","--fail","--location","--silent","--show-error","--proto","=https","--proto-redir","=https","--max-time","40","--max-filesize","8388608","--cacert",base+"ca-certificates.crt","-o","/tmp/muse-media-source",u}));return "/tmp/muse-media-source";}
static int eq_read(int* value){return __atomic_load_n(value,__ATOMIC_RELAXED);}
static void eq_write(int* value,int next){__atomic_store_n(value,next,__ATOMIC_RELAXED);}
static void pump_audio(int input,int output){
 setpriority(PRIO_PROCESS,syscall(SYS_gettid),-8);muse_audio::Equalizer eq;muse_audio::Spectrum spectrum;alignas(int16_t) unsigned char buffer[4100];size_t carry=0;
 while(true){ssize_t n=read(input,buffer+carry,4096);if(n<0&&errno==EINTR)continue;if(n<=0)break;size_t bytes=carry+n,whole=bytes-bytes%4;std::array<double,10> gains;for(int i=0;i<10;i++)gains[i]=(eq_read(&s->sw_eq)?eq_read(&s->eq_gain[i])/10.0:0);eq.configure(gains);eq.process(reinterpret_cast<int16_t*>(buffer),whole/4);eq_write(&s->audio_blocks,eq_read(&s->audio_blocks)+1);if(spectrum.process(reinterpret_cast<int16_t*>(buffer),whole/4)){for(int i=0;i<10;i++)eq_write(&s->eq_level[i],int(spectrum.levels()[i]*1000));eq_write(&s->spectrum_version,eq_read(&s->spectrum_version)+1);}size_t sent=0;while(sent<whole){ssize_t count=write(output,buffer+sent,whole-sent);if(count<0&&errno==EINTR)continue;if(count<=0){eq_write(&s->audio_running,0);close(input);close(output);return;}sent+=count;}carry=bytes-whole;memmove(buffer,buffer+whole,carry);}
 close(input);close(output);for(int i=0;i<10;i++)eq_write(&s->eq_level[i],0);eq_write(&s->spectrum_version,eq_read(&s->spectrum_version)+1);eq_write(&s->audio_running,0);
}
static int eq_band(int x,int y){if(s->full||s->eq_view!=1||x<704||x>=1000)return -1;int row=y>=329?1:0;int top=row?329:177;if(y<top-10||y>top+107)return -1;int column=std::clamp((x-704)/59,0,4);return row*5+column;}
static void eq_adjust(int band,int y){int top=band>=5?329:177;int gain=std::clamp(int(std::lround((top+45-y)*120.0/45.0)),-120,120);eq_write(&s->eq_gain[band],gain);s->eq_version++;s->version++;}
static std::array<int,5> hw_gains(){std::array<int,5> result;for(int i=0;i<5;i++)result[i]=s->hw_gain[i];return result;}
static void codec_eq(bool enabled){if(!codec||!codec->available())throw std::runtime_error("NAU8822 codec unavailable");codec->equalizer(hw_gains(),enabled);s->hw_eq=enabled;s->eq_version++;}
static void dsp_control(std::string feature,bool enabled){
 if(feature=="software_eq")eq_write(&s->sw_eq,enabled);
 else if(feature=="hardware_eq")codec_eq(enabled);
 else {const char* name=nullptr;int* flag=nullptr;bool enumeration=false;int value=enabled;
  if(feature=="limiter"){name="DAC Limiter Switch";flag=&s->limiter;}
  else if(feature=="mic_hpf"){name="High Pass Filter Switch";flag=&s->mic_hpf;}
  else if(feature=="mic_alc"){name="ALC Enable Switch";flag=&s->mic_alc;enumeration=true;value=enabled?3:0;}
  else if(feature=="mic_gate"){name="ALC Noise Gate Switch";flag=&s->mic_gate;}
  else throw std::runtime_error("unknown DSP feature");
  if(!codec||!codec->available())throw std::runtime_error("NAU8822 codec unavailable");codec->set(name,value,enumeration);*flag=enabled;
 }s->eq_version++;s->version++;
}
static void eq_default(){if(codec&&codec->available())codec->equalizer({},false);for(auto& gain:s->eq_gain)eq_write(&gain,0);for(auto& gain:s->hw_gain)gain=0;s->hw_eq=0;eq_write(&s->sw_eq,1);s->eq_version++;s->version++;}
static void hw_adjust(int band,int gain){if(band<0||band>=5||gain<-12||gain>12)throw std::runtime_error("hardware EQ band must be 0..4 and gain -12..12 dB");auto next=hw_gains();next[band]=gain;if(!codec||!codec->available())throw std::runtime_error("NAU8822 codec unavailable");codec->equalizer(next,s->hw_eq);s->hw_gain[band]=gain;s->eq_version++;s->version++;}
static void tune(J q){
 std::string preset=q.value("preset",std::string()),engine=q.value("engine",std::string("active"));
 double amount=q.value("amount_db",3.0);if(!std::isfinite(amount)||amount<0||amount>12)throw std::runtime_error("amount_db must be 0..12");
 if(engine=="active")engine=s->hw_eq&&!s->sw_eq?"hardware":"software";
 if(engine!="software"&&engine!="hardware")throw std::runtime_error("engine must be active, software or hardware");
 if(preset=="flat"){eq_default();return;}
 if(preset!="bass_up"&&preset!="bass_down"&&preset!="treble_up"&&preset!="treble_down"&&preset!="voice"&&preset!="music")throw std::runtime_error("unknown tone preset");
 bool hardware=engine=="hardware";int count=hardware?5:10;std::array<int,10> gains{};
 for(int i=0;i<count;i++)gains[i]=hardware?s->hw_gain[i]*10:eq_read(&s->eq_gain[i]);
 if(preset=="voice"||preset=="music"){
  const int voice_sw[]={-3,-3,-2,0,2,3,3,1,0,0},music_sw[]={3,3,2,0,-1,0,1,2,2,1};
  const int voice_hw[]={-3,-1,2,3,0},music_hw[]={3,1,0,2,2};
  for(int i=0;i<count;i++)gains[i]=10*(hardware?(preset=="voice"?voice_hw[i]:music_hw[i]):(preset=="voice"?voice_sw[i]:music_sw[i]));
 }else{bool bass=preset.find("bass")==0;int step=int(std::lround(amount*10))*(preset.find("down")!=std::string::npos?-1:1);for(int i=0;i<count;i++)if(bass?(i<(hardware?2:3)):(i>=(hardware?3:7)))gains[i]=std::clamp(gains[i]+step,-120,120);}
 if(hardware){auto next=hw_gains();for(int i=0;i<5;i++)next[i]=int(std::lround(gains[i]/10.0));if(!codec||!codec->available())throw std::runtime_error("NAU8822 codec unavailable");codec->equalizer(next,true);for(int i=0;i<5;i++)s->hw_gain[i]=next[i];s->hw_eq=1;}
 else {for(int i=0;i<10;i++)eq_write(&s->eq_gain[i],gains[i]);eq_write(&s->sw_eq,1);}
 s->eq_version++;s->version++;
}
static int hw_band(int x,int y){return !s->full&&s->eq_view==2&&x>=704&&x<999&&y>=212&&y<=372?(x-704)/59:-1;}
static void hw_slider(int band,int y){hw_adjust(band,std::clamp(int(std::lround((292-y)*12.0/70.0)),-12,12));}
struct Renderer {
 int fd;unsigned char *fb;size_t bytes=4096*600,mapped=4096*600;fb_var_screeninfo screen{};bool flip=false;std::vector<unsigned char> composed=std::vector<unsigned char>(4096*600);std::string cachekey;std::vector<unsigned char> fonts;stbtt_fontinfo font{};bool hasfont=false;
 Renderer(){fd=open(fbpath.c_str(),O_RDWR);if(fd<0)throw std::runtime_error("framebuffer unavailable");if(fbpath=="/dev/fb0"){fb_var_screeninfo v{};fb_fix_screeninfo f{};if(ioctl(fd,FBIOGET_VSCREENINFO,&v)||ioctl(fd,FBIOGET_FSCREENINFO,&f)||v.xres!=1024||v.yres!=600||v.bits_per_pixel!=32||f.line_length!=4096)throw std::runtime_error("unsupported framebuffer geometry");screen=v;flip=getenv("MUSE_FB_PAGE_FLIP")&&v.yres_virtual>=1200&&f.smem_len>=bytes*2;if(flip)mapped=bytes*2;}fb=(unsigned char*)mmap(nullptr,mapped,PROT_READ|PROT_WRITE,MAP_SHARED,fd,0);if(fb==MAP_FAILED)throw std::runtime_error("cannot map framebuffer");try{auto data=readfile(base+"font.ttf",2000000);fonts.assign(data.begin(),data.end());hasfont=stbtt_InitFont(&font,fonts.data(),0);}catch(...){} }
 ~Renderer(){munmap(fb,mapped);close(fd);}
 void pixel(int x,int y,int r,int g,int b){if(x<0||x>=1024||y<0||y>=600)return;size_t i=((599-y)*1024+1023-x)*4;composed[i]=b;composed[i+1]=g;composed[i+2]=r;composed[i+3]=255;}
 void rect(int x,int y,int w,int h,int r,int g,int b){int left=std::max(0,x),right=std::min(1024,x+w),top=std::max(0,y),bottom=std::min(600,y+h);if(right<=left||bottom<=top)return;uint32_t color=0xff000000u|(r<<16)|(g<<8)|b;auto pixels=reinterpret_cast<uint32_t*>(composed.data());for(int j=top;j<bottom;j++)std::fill(pixels+(599-j)*1024+1024-right,pixels+(599-j)*1024+1024-left,color);}
 void text(std::string t,int x,int y,int size=20,int wrap=980,int color=0x253047){if(!hasfont)return;float scale=stbtt_ScaleForPixelHeight(&font,size);int start=x;for(unsigned char c:t){if(c=='\n'||x>wrap){x=start;y+=size+7;if(c=='\n')continue;}if(y>590)break;int w,h,dx,dy,advance;auto bitmap=stbtt_GetCodepointBitmap(&font,0,scale,c,&w,&h,&dx,&dy);for(int j=0;j<h;j++)for(int i=0;i<w;i++){int q=bitmap[j*w+i],px=x+dx+i,py=y+size+dy+j;if(q&&px>=0&&px<1024&&py>=0&&py<600){size_t offset=((599-py)*1024+1023-px)*4;pixel(px,py,(((color>>16)&255)*q+composed[offset+2]*(255-q))/255,(((color>>8)&255)*q+composed[offset+1]*(255-q))/255,((color&255)*q+composed[offset]*(255-q))/255);}}stbtt_FreeBitmap(bitmap,nullptr);stbtt_GetCodepointHMetrics(&font,c,&advance,nullptr);x+=int(advance*scale);}}
 void asset(const char* name,int x,int y,int width,int height){int w,h,n;unsigned char* img=stbi_load((base+"assets/"+name).c_str(),&w,&h,&n,4);if(!img)return;for(int j=0;j<height;j++)for(int i=0;i<width;i++){const unsigned char* p=img+((j*h/height)*w+i*w/width)*4;int px=x+i,py=y+j;size_t offset=((599-py)*1024+1023-px)*4;int q=p[3];pixel(px,py,(p[0]*q+composed[offset+2]*(255-q))/255,(p[1]*q+composed[offset+1]*(255-q))/255,(p[2]*q+composed[offset]*(255-q))/255);}stbi_image_free(img);}
 void circle(int cx,int cy,int radius,int r,int g,int b){for(int y=-radius;y<=radius;y++)for(int x=-radius;x<=radius;x++)if(x*x+y*y<=radius*radius)pixel(cx+x,cy+y,r,g,b);}
 void chrome(std::string caption,bool video){
  std::string key=caption+std::to_string(s->full)+std::to_string(s->temperature)+std::to_string(s->volume)+std::to_string(s->muted)+std::to_string(video)+std::to_string(s->eq_view)+std::to_string(s->eq_version)+s->state+std::to_string(s->paused);
  if(key==cachekey){rect(s->full?0:24,s->full?0:124,s->full?1024:650,s->full?600:348,245,247,251);return;}
  rect(0,0,1024,600,244,246,252);
  if(!s->full){
   rect(0,0,1024,96,255,255,255);asset("muse-logo.png",24,12,72,72);text("Muse",109,22,36);text("MA35D1 CPU by Nuvoton",260,13,30,925);text("featuring HW Audio Codec NAU8822 by Nuvoton",260,57,22,925,0x68758a);asset("jollybot.png",934,9,72,78);
   rect(24,112,650,392,255,255,255);text(caption.substr(0,65),38,478,17,660,0x68758a);
   rect(24,124,650,348,245,247,251);rect(688,112,316,480,255,255,255);
   const char* tabs[]={"Room","10 EQ","5 HW EQ","DSP"};for(int i=0;i<4;i++){rect(704+i*74,120,70,34,i==s->eq_view?232:245,i==s->eq_view?239:247,251);text(tabs[i],709+i*74,127,15,777+i*74);}
   if(s->eq_view==1){
    const char* labels[]={"31","63","125","250","500","1k","2k","4k","8k","16k"};
    for(int band=0;band<10;band++){int x=710+(band%5)*59,top=band>=5?329:177;rect(x+10,top,6,91,218,225,236);rect(x+2,top+45,36,1,184,196,213);int gain=eq_read(&s->eq_gain[band]);int handle=top+45-gain*45/120;rect(x+1,handle-7,31,14,45,108,217);text(labels[band],x,top+115,15,x+55);char value[20];snprintf(value,sizeof(value),"%+.1f",gain/10.0);text(value,x,top+96,14,x+55,0x68758a);}
    text(s->sw_eq?"CPU EQ ON | Spectrum before codec":"CPU EQ OFF | Spectrum before codec",709,464,15,998,0x68758a);
   }else if(s->eq_view==2){
    text("NAU8822 by Nuvoton",714,168,22);text(s->hw_eq?"ON - runs inside codec":"OFF - unity gain; settings retained",714,198,16,998,0x68758a);
    const char* labels[]={"105","300","850","2.4k","6.9k"};for(int i=0;i<5;i++){int x=710+i*59;rect(x+20,222,6,141,218,225,236);rect(x+1,292,49,1,184,196,213);rect(x+5,292-s->hw_gain[i]*70/12-7,36,14,45,108,217);text(labels[i],x,402,16,x+55);text(std::to_string(s->hw_gain[i])+"dB",x,377,15,x+55);}
    rect(708,441,138,44,232,239,251);text(s->hw_eq?"HW EQ: ON":"HW EQ: OFF",715,454,17);rect(852,441,144,44,232,239,251);text("EQ Default",866,454,17);
   }else if(s->eq_view==3){
    const char* names[]={"10-band CPU EQ","5-band codec EQ","Codec DAC limiter","Mic high-pass","Mic auto gain","Mic noise gate"};int flags[]={s->sw_eq,s->hw_eq,s->limiter,s->mic_hpf,s->mic_alc,s->mic_gate};
    for(int i=0;i<6;i++){int y=170+i*46;rect(708,y,288,40,245,247,251);text(names[i],717,y+10,18,919);rect(929,y+3,61,34,flags[i]?38:220,flags[i]?173:225,flags[i]?153:236);text(flags[i]?"ON":"OFF",942,y+11,16,994,flags[i]?0xffffff:0x253047);}
    rect(708,453,288,46,232,239,251);text("EQ Default (flat)",775,467,18);
   }else{
    text("Room 72 F  |  Heating",720,160,18,990,0x68758a);circle(852,290,115,205,212,223);circle(852,290,108,120,69,42);text(std::to_string(s->temperature),805,237,64,975,0xffffff);text("Target F",815,313,20,975,0xffffff);rect(725,411,67,50,232,239,251);rect(912,411,67,50,232,239,251);text("-",748,420,30);text("+",934,420,30);text("Heat mode",806,467,18,990,0x68758a);
   }
   rect(24,524,650,59,232,239,251);
   text(video?((!strcmp(s->state,"ended")||!strcmp(s->state,"stopped"))?"Replay":(s->paused?"Resume":"Pause")):"Fit",34,541,17);text("- Zoom",130,541,17);text("+ Zoom",220,541,17);if(video)text("EQ Default",307,541,17);else{text("<",322,541,20);text(">",382,541,20);}text("Full screen",450,541,17);text("Stop",610,541,17);
   text(s->muted?"Headphones muted":"Headphones "+std::to_string(s->volume)+"%",721,516,18);
   rect(704,550,296,42,232,239,251);text("-",730,553,26);text(s->muted?"Unmute":"Mute",809,558,18);text("+",956,553,26);
  }else{rect(840,0,184,88,232,239,251);text("Exit full",856,26,26);}
  cachekey=key;
 }
 void spectrum_bars(){if(s->full||s->eq_view!=1)return;for(int band=0;band<10;band++){int x=750+(band%5)*59,top=band>=5?329:177;rect(x,top,11,91,235,240,249);int height=eq_read(&s->eq_level[band])*91/1000;rect(x,top+91-height,11,height,38,173,153);}rect(708,490,289,20,255,255,255);text(s->paused?"Spectrum paused":(eq_read(&s->audio_running)?"Spectrum LIVE":(!strcmp(s->state,"ended")?"Track ended - tap Replay":"No audio playing")),714,490,14,998,0x68758a);}
 void present(){if(flip){screen.yoffset=screen.yoffset?0:600;memcpy(fb+screen.yoffset*4096,composed.data(),bytes);screen.activate=FB_ACTIVATE_VBL;if(ioctl(fd,FBIOPAN_DISPLAY,&screen)){flip=false;memcpy(fb,composed.data(),bytes);}}else memcpy(fb,composed.data(),bytes);}
 void image(const unsigned char*rgb,int w,int h,std::string caption,bool video=false){chrome(caption,video);int vx=s->full?0:24,top=s->full?0:124,vw=s->full?1024:650,vh=s->full?600:348;float scale=std::min(float(vw)/w,float(vh)/h)*s->zoom;if(video&&!s->full)scale=std::min(scale,1.15f*s->zoom);float left=vx+(vw-w*scale)/2+s->panx,up=top+(vh-h*scale)/2+s->pany;int x0=std::max(vx,int(std::ceil(left))),x1=std::min(vx+vw,int(std::ceil(left+w*scale))),y0=std::max(top,int(std::ceil(up))),y1=std::min(top+vh,int(std::ceil(up+h*scale)));int samples[1024];for(int x=x0;x<x1;x++)samples[x]=std::clamp(int((x-left)/scale),0,w-1);for(int y=y0;y<y1;y++){int sy=std::clamp(int((y-up)/scale),0,h-1);for(int x=x0;x<x1;x++){const unsigned char*p=rgb+(sy*w+samples[x])*3;pixel(x,y,p[0],p[1],p[2]);}}if(s->full){rect(840,0,184,88,232,239,251);text("Exit full",856,26,26);}spectrum_bars();present();s->frames++;}
};
static std::string kind(J p){std::string k=p.value("kind","auto"),u=p.value("url","");if(k!="auto")return k;auto end=u.find('?');std::string path=u.substr(0,end);std::transform(path.begin(),path.end(),path.begin(),::tolower);if(u.find("youtu.be/")!=std::string::npos||u.find("youtube.com/")!=std::string::npos)return "youtube";auto dot=path.rfind('.');std::string ext=dot==std::string::npos?"":path.substr(dot+1);if(ext=="pdf")return "pdf";if(ext=="svg")return "svg";if(ext=="gif")return "animation";for(auto e:{"png","jpg","jpeg","webp","bmp","tga","psd","hdr","pnm"})if(ext==e)return "image";for(auto e:{"mp3","wav","flac","ogg","opus","aac","m4a"})if(ext==e)return "audio";for(auto e:{"mp4","webm","mkv","mov","avi","m3u8","mpd","ts","flv"})if(ext==e)return "video";if(p.contains("text"))return "text";for(auto e:{"txt","md","json","csv","log","html","htm"})if(ext==e)return "text";return "unknown";}
struct VC8KPP {int enable_pp,frame_buf_paddr,frame_buff_size,frame_buf_w,frame_buf_h,img_out_x,img_out_y,img_out_w,img_out_h,img_out_fmt,rotation,pp_out_dst,libjpeg_mode,reserved[8];};
static bool configure_decoder(){int fd=open("/dev/video0",O_RDWR);if(fd<0)return false;VC8KPP pp{};pp.frame_buf_w=1024;pp.frame_buf_h=600;pp.img_out_w=640;pp.img_out_h=360;pp.img_out_fmt=V4L2_PIX_FMT_NV12;bool ok=ioctl(fd,_IOW('v',91,VC8KPP),&pp)>=0;close(fd);return ok;}
static void play(J p){
 try {setpgid(0,0);struct rlimit mem{128*1024*1024,128*1024*1024},fs{9*1024*1024,9*1024*1024};setrlimit(RLIMIT_AS,&mem);setrlimit(RLIMIT_FSIZE,&fs);struct rlimit stack{1024*1024,1024*1024};setrlimit(RLIMIT_STACK,&stack);int active=open("/tmp/muse-native-media.active",O_CREAT|O_WRONLY,0600);if(active>=0)close(active);state("loading");std::string k=kind(p),u=p.value("url",""),caption=p.value("caption","Muse media");Renderer r;
 if(k=="text"){std::string txt=p.contains("text")?p["text"].get<std::string>():readfile(fetch(u),256*1024);state(p.value("_state",std::string("ready")).c_str());int last=-1;while(true){if(last!=s->version){r.chrome(caption,p.value("_controls",false));r.text(txt,24+int(s->panx),124+int(s->pany),int(20*s->zoom));last=s->version;r.present();s->frames++;}usleep(25000);}}
 if(k=="image"||k=="pdf"||k=="svg") {std::string path=fetch(u);int last=-1,prevpage=-1,w=0,h=0,n=0;unsigned char *img=nullptr;state("ready");while(true){if(prevpage!=s->page){if(img)stbi_image_free(img);std::string raster=path;if(k!="image"){waitok(spawn({base+"mutool","draw","-q","-F","png","-w","1400","-h","1400","-o","/tmp/muse-media-page.png",path,std::to_string(s->page)}));raster="/tmp/muse-media-page.png";}if(!stbi_info(raster.c_str(),&w,&h,&n)||w>4096||h>4096||int64_t(w)*h>4000000)throw std::runtime_error("image too large or unsupported");img=stbi_load(raster.c_str(),&w,&h,&n,3);if(!img)throw std::runtime_error("image too large or unsupported");prevpage=s->page;}if(last!=s->version){r.image(img,w,h,caption+" | page "+std::to_string(s->page));last=s->version;}usleep(25000);}}
 if(k=="youtube"){if(!exists(base+"youtube-resolve"))throw std::runtime_error("YouTube watch URL resolver not installed; provide a direct HTTPS video/HLS URL");int fd=open("/tmp/muse-media-resolved",O_CREAT|O_TRUNC|O_RDWR,0600);waitok(spawn({base+"youtube-resolve",u},-1,fd));close(fd);u=readfile("/tmp/muse-media-resolved",8192);while(!u.empty()&&isspace(u.back()))u.pop_back();if(u.rfind("https://",0)!=0)throw std::runtime_error("resolver did not return HTTPS media");k="video";unlink("/tmp/muse-youtube.html");unlink("/tmp/muse-youtube-player.json");unlink("/tmp/muse-youtube-request.json");unlink("/tmp/muse-media-resolved");}
 if(k=="video"||k=="audio"||k=="animation"){
  std::string input=u;if(input.rfind("https://",0)!=0&&input.rfind("/opt/muse-media/assets/",0)!=0)throw std::runtime_error("HTTPS media or a board asset required");
  std::string metadata;
  if(k=="video"){int probe[2];if(pipe(probe))throw std::runtime_error("cannot create probe pipe");std::vector<std::string> probe_args{base+"ffmpeg","-nostdin","-hide_banner","-rw_timeout","15000000"};if(input.rfind("https://",0)==0)probe_args.insert(probe_args.end(),{"-tls_verify","1","-ca_file",base+"ca-certificates.crt"});probe_args.insert(probe_args.end(),{"-i",input});pid_t pp=spawn(probe_args,-1,probe[1],-1,true);close(probe[1]);char buf[1024];ssize_t n;while((n=read(probe[0],buf,sizeof(buf)))>0){if(metadata.size()<16384)metadata.append(buf,n);}close(probe[0]);waitpid(pp,nullptr,0);}
  bool hardware=false&&k=="video"&&metadata.find("Video: h264")!=std::string::npos&&configure_decoder();
  std::vector<std::string> args{base+"ffmpeg","-nostdin","-v","info","-threads","1","-filter_threads","1","-filter_complex_threads","1","-rw_timeout","15000000"};if(input.rfind("https://",0)==0)args.insert(args.end(),{"-tls_verify","1","-ca_file",base+"ca-certificates.crt"});if(k=="animation")args.insert(args.end(),{"-stream_loop","-1"});if(hardware)args.insert(args.end(),{"-c:v","h264_v4l2m2m","-num_output_buffers","4","-num_capture_buffers","6"});args.insert(args.end(),{"-re","-i",input});
  int audiofd[2]={-1,-1},pcmfd[2]={-1,-1};std::thread audio_pump;pid_t player=0,audio_decoder=0;bool audio=k=="video"&&p.value("audio",true)&&metadata.find("Audio:")!=std::string::npos;
  std::vector<unsigned char> last_frame;int pipefd[2];if(pipe(pipefd))throw std::runtime_error("cannot create decoder pipe");if(k=="audio")args.insert(args.end(),{"-vn","-threads","1","-f","s16le","-ac","2","-ar","48000","pipe:1"});else args.insert(args.end(),{"-an","-vf","scale=480:270:force_original_aspect_ratio=decrease,pad=480:270:(ow-iw)/2:(oh-ih)/2,fps=20","-pix_fmt","rgb24","-threads","1","-f","rawvideo","pipe:1"});
  if(audio||k=="audio"){if(pipe(pcmfd))throw std::runtime_error("cannot create EQ pipe");if(audio&&pipe(audiofd))throw std::runtime_error("cannot create audio pipe");player=spawn({"/usr/bin/aplay","-q","--buffer-size=8192","--period-size=1024","-D","hw:0,0","-t","raw","-f","S16_LE","-c","2","-r","48000"},pcmfd[0]);close(pcmfd[0]);
   if(audio){std::vector<std::string> audio_args{base+"ffmpeg","-nostdin","-v","error","-threads","1","-filter_threads","1","-rw_timeout","15000000"};if(input.rfind("https://",0)==0)audio_args.insert(audio_args.end(),{"-tls_verify","1","-ca_file",base+"ca-certificates.crt"});audio_args.insert(audio_args.end(),{"-i",input,"-vn","-threads","1","-f","s16le","-ac","2","-ar","48000","pipe:1"});audio_decoder=spawn(audio_args,-1,audiofd[1]);close(audiofd[1]);s->audio_decoder_pid=audio_decoder;setpriority(PRIO_PROCESS,audio_decoder,-5);setpriority(PRIO_PROCESS,player,-10);}}
  pid_t decoder=spawn(args,-1,pipefd[1]);s->decoder_pid=decoder;s->audio_pid=player;close(pipefd[1]);if(audio||k=="audio"){eq_write(&s->audio_running,1);audio_pump=std::thread(pump_audio,audio?audiofd[0]:pipefd[0],pcmfd[1]);}state("playing");if(k=="audio"){while(eq_read(&s->audio_running)){r.chrome(caption,true);r.text("Audio playing through headphones",40,160,28);r.spectrum_bars();r.present();s->frames++;usleep(80000);}audio_pump.join();waitok(player);}else{
   std::mutex lock;std::condition_variable changed;std::vector<unsigned char> latest(480*270*3);bool finished=false,truncated=false;unsigned sequence=0;
   std::thread reader([&]{std::vector<unsigned char> next(latest.size());while(true){size_t used=0;while(used<next.size()){ssize_t count=read(pipefd[0],next.data()+used,next.size()-used);if(count<=0)break;used+=count;}if(used!=next.size()){std::lock_guard<std::mutex> guard(lock);finished=true;truncated=used!=0;changed.notify_one();break;}{std::lock_guard<std::mutex> guard(lock);next.swap(latest);sequence++;}changed.notify_one();}});
   unsigned shown=0;int view=-1,meter=-1;double presented=0;std::vector<unsigned char> frame(latest.size());while(true){std::unique_lock<std::mutex> guard(lock);changed.wait_for(guard,std::chrono::milliseconds(50),[&]{return shown!=sequence||view!=s->version||meter!=eq_read(&s->spectrum_version)||(finished&&!eq_read(&s->audio_running));});bool fresh=shown!=sequence;if(fresh){frame=latest;shown=sequence;}bool done=finished;if((fresh||view!=s->version||meter!=eq_read(&s->spectrum_version))&&shown){view=s->version;meter=eq_read(&s->spectrum_version);guard.unlock();double delay=.05-(now()-presented);if(delay>0)usleep(int(delay*1000000));r.image(frame.data(),480,270,caption,true);presented=now();}else guard.unlock();if(done&&!eq_read(&s->audio_running))break;}
   reader.join();if(truncated)throw std::runtime_error("truncated video frame");last_frame=std::move(frame);close(pipefd[0]);}
  waitok(decoder);if(audio){audio_pump.join();waitok(audio_decoder);waitok(player);}s->decoder_pid=s->audio_pid=s->audio_decoder_pid=0;s->version++;state("ended");int last=-1;while(true){if(last!=s->version){if(!last_frame.empty())r.image(last_frame.data(),480,270,caption,true);else{r.chrome(caption,true);r.spectrum_bars();r.text("Playback finished - tap Replay",40,160,28);r.present();}last=s->version;}usleep(25000);}
 }
 throw std::runtime_error("unsupported media type; query media.capabilities");
 }catch(const std::exception& e){snprintf(s->error,sizeof(s->error),"%s",e.what());state("error");_exit(1);}
}
static void stop(){if(worker>0){kill(-worker,SIGCONT);kill(-worker,SIGTERM);for(int i=0;i<20;i++){if(waitpid(worker,nullptr,WNOHANG)==worker){worker=0;break;}usleep(10000);}if(worker){kill(-worker,SIGKILL);waitpid(worker,nullptr,0);worker=0;}}unlink("/tmp/muse-native-media.active");s->decoder_pid=s->audio_pid=s->audio_decoder_pid=0;eq_write(&s->audio_running,0);for(auto& level:s->eq_level)eq_write(&level,0);s->paused=0;state("stopped");}
static void stop_display(){stop();s->full=0;s->version++;worker=fork();if(worker==0){play({{"kind","text"},{"text","Playback stopped. Tap Replay to start again."},{"caption",current.value("caption",std::string("Muse media"))},{"_state","stopped"},{"_controls",true}});_exit(0);}if(worker<0)throw std::runtime_error("cannot start display worker");setpgid(worker,worker);}
static J capabilities(){return {{"equalizer",{{"software_bands",10},{"codec","NAU8822"},{"hardware_bands",5},{"hardware_hz",{105,300,850,2400,6900}},{"gain_db",{-12,12}},{"hardware_off","unity gain; settings retained"},{"spectrum_tap","PCM before codec DSP"},{"switches",{"software_eq","hardware_eq","limiter","mic_hpf","mic_alc","mic_gate"}}}},{"runtime","board-native"},{"internet","board Ethernet via ICS; no laptop media process"},{"image",{"PNG","JPEG","WebP","BMP","TGA","PSD","HDR","PNM"}},{"text",{"plain text","Markdown as text","JSON as text","CSV as text"}},{"video_backend",exists(base+"ffmpeg")},{"h264_hardware_device",access("/dev/video0",F_OK)==0},{"gpu_device",access("/dev/galcore",F_OK)==0},{"video",{"MP4/H.264","WebM/VP8/VP9","MKV","MOV","AVI","MPEG-TS","HLS"}},{"audio",{"PCM/WAV","MP3","AAC/M4A","FLAC","Ogg/Vorbis","Opus"}},{"pdf",exists(base+"mutool")},{"svg",exists(base+"mutool")},{"animation",exists(base+"ffmpeg")},{"youtube_watch_urls",exists(base+"youtube-resolve")},{"pinch",false},{"touch",{"drag pan/scroll","double tap zoom","zoom buttons","full screen toggle"}},{"limits",{{"download_bytes",8388608},{"video_resolution","480x270"},{"video_fps",20},{"video_audio",true},{"drm",false}}}};}
static J request(J p){std::string action=p.value("action","");if(action=="audio.tune"){tune(p.value("params",J::object()));J result=request({{"action","media.status"}});result["payload"]["preset"]=p["params"].value("preset",std::string());return result;}if(action=="media.capabilities")return {{"ok",true},{"payload",capabilities()}};if(action=="media.status")return {{"ok",true},{"payload",{{"state",s->state},{"error",s->error},{"frames",s->frames},{"queued",pending.size()},{"zoom",s->zoom},{"page",s->page},{"fullscreen",bool(s->full)},{"paused",bool(s->paused)},{"temperature_f",s->temperature},{"volume_percent",s->volume},{"muted",bool(s->muted)},{"equalizer_db",J::array({eq_read(&s->eq_gain[0])/10.0,eq_read(&s->eq_gain[1])/10.0,eq_read(&s->eq_gain[2])/10.0,eq_read(&s->eq_gain[3])/10.0,eq_read(&s->eq_gain[4])/10.0,eq_read(&s->eq_gain[5])/10.0,eq_read(&s->eq_gain[6])/10.0,eq_read(&s->eq_gain[7])/10.0,eq_read(&s->eq_gain[8])/10.0,eq_read(&s->eq_gain[9])/10.0})},{"software_eq_enabled",bool(s->sw_eq)},{"hardware_eq_enabled",bool(s->hw_eq)},{"hardware_eq_db",J::array({s->hw_gain[0],s->hw_gain[1],s->hw_gain[2],s->hw_gain[3],s->hw_gain[4]})},{"dsp",{{"available",bool(s->codec_available)},{"limiter",bool(s->limiter)},{"mic_hpf",bool(s->mic_hpf)},{"mic_alc",bool(s->mic_alc)},{"mic_gate",bool(s->mic_gate)}}},{"audio_running",bool(eq_read(&s->audio_running))},{"audio_blocks",eq_read(&s->audio_blocks)},{"spectrum_updates",eq_read(&s->spectrum_version)},{"spectrum",J::array({eq_read(&s->eq_level[0]),eq_read(&s->eq_level[1]),eq_read(&s->eq_level[2]),eq_read(&s->eq_level[3]),eq_read(&s->eq_level[4]),eq_read(&s->eq_level[5]),eq_read(&s->eq_level[6]),eq_read(&s->eq_level[7]),eq_read(&s->eq_level[8]),eq_read(&s->eq_level[9])})}}}};
 if(action=="media.enqueue"){J q=p.value("params",J::object());if(!q.is_object()||pending.size()>=8)throw std::runtime_error("invalid media or queue full");pending.push_back(q);return {{"ok",true},{"payload",{{"queued",pending.size()}}}};}
 if(action=="media.show") {J q=p.value("params",J::object());if(q.value("hardware",false))throw std::runtime_error("VC8000 decoding quarantined following a kernel hang; software playback is available");if(!q.is_object())throw std::runtime_error("params must be an object");std::string k=kind(q);if(k=="unknown")throw std::runtime_error("kind required for URLs without a media extension");if(k=="youtube"&&!exists(base+"youtube-resolve"))throw std::runtime_error("YouTube resolver unavailable; supply direct HTTPS video/HLS URL");if((k=="pdf"||k=="svg")&&!exists(base+"mutool"))throw std::runtime_error("PDF/SVG renderer unavailable");if((k=="video"||k=="audio"||k=="animation")&&!exists(base+"ffmpeg"))throw std::runtime_error("FFmpeg backend unavailable");if(q.value("text",std::string()).size()>262144)throw std::runtime_error("text too large");stop();s->zoom=1;s->panx=s->pany=0;s->paused=0;s->frames=0;s->decoder_pid=s->audio_pid=s->audio_decoder_pid=0;s->error[0]=0;s->audio_blocks=0;s->eq_version++;s->version++;s->full=q.value("fullscreen",false);s->page=q.value("page",1);if(s->page<1||s->page>10000)throw std::runtime_error("invalid page");current=q;worker=fork();if(worker==0){play(q);_exit(0);}if(worker<0)throw std::runtime_error("cannot start media worker");setpgid(worker,worker);return {{"ok",true},{"payload",{{"accepted",true},{"kind",k}}}};}
 if(action=="media.control"){J q=p.value("params",J::object());std::string op=q.value("operation","");if(op=="stop"){stop_display();return {{"ok",true}};}if(op=="pause"||op=="resume"){if(worker<=0)throw std::runtime_error("no active media");if(s->decoder_pid>0)kill(s->decoder_pid,op=="pause"?SIGSTOP:SIGCONT);if(s->audio_pid>0)kill(s->audio_pid,op=="pause"?SIGSTOP:SIGCONT);if(s->audio_decoder_pid>0)kill(s->audio_decoder_pid,op=="pause"?SIGSTOP:SIGCONT);s->paused=op=="pause";s->version++;return {{"ok",true}};}if(op=="replay"){if(current.empty())throw std::runtime_error("no previous media");return request({{"action","media.show"},{"params",current}});}if(op=="dsp"){dsp_control(q.value("feature",std::string()),q.value("enabled",true));}else if(op=="hardware_equalizer"){double gain=q.value("value",0.0);if(!std::isfinite(gain)||gain<-12||gain>12)throw std::runtime_error("hardware gain must be -12..12 dB");hw_adjust(q.value("band",-1),int(std::lround(gain)));}else if(op=="eq_default"){eq_default();}else if(op=="equalizer"){int band=q.value("band",-1);double gain=q.value("value",0.0);if(band<0||band>=10||!std::isfinite(gain)||gain<-12||gain>12)throw std::runtime_error("EQ band must be 0..9 and gain -12..12 dB");eq_write(&s->eq_gain[band],int(std::lround(gain*10)));s->eq_version++;}else if(op=="eq_flat"){for(auto& gain:s->eq_gain)eq_write(&gain,0);s->eq_version++;}else if(op=="eq_view"){int view=q.value("value",q.value("enabled",true)?1:0);if(view<0||view>3)throw std::runtime_error("view must be 0..3");s->eq_view=view;}else if(op=="fullscreen")s->full=q.value("enabled",!bool(s->full));else if(op=="zoom"){float value=q.value("value",1.f);if(!std::isfinite(value)||value<1||value>4)throw std::runtime_error("zoom must be 1..4");s->zoom=value;}else if(op=="pan"){s->panx=std::clamp(q.value("x",0.f),-8192.f,8192.f);s->pany=std::clamp(q.value("y",0.f),-8192.f,8192.f);}else if(op=="page"){int value=q.value("value",1);if(value<1||value>10000)throw std::runtime_error("invalid page");s->page=value;}else if(op=="fit"){s->zoom=1;s->panx=s->pany=0;}else throw std::runtime_error("unknown media operation");s->version++;return {{"ok",true}};}
 throw std::runtime_error("unknown action");}
static void touch(int x,int y,int dx,int dy,bool release,bool drag,double duration){
 static double lasttap=0;
 if(!release){if((x>=24&&x<674&&y>=124&&y<504)||s->full){s->panx+=dx;s->pany+=dy;s->version++;}return;}
 if(drag||duration>.8)return;
 if(s->full&&x>=820&&y<120)s->full=0;
 else if(!s->full&&x>=704){
  if(y>=100&&y<166)s->eq_view=std::clamp((x-704)/74,0,3);
  if(s->eq_view==3&&y>=170&&y<446){int row=(y-170)/46;const char* features[]={"software_eq","hardware_eq","limiter","mic_hpf","mic_alc","mic_gate"};int flags[]={s->sw_eq,s->hw_eq,s->limiter,s->mic_hpf,s->mic_alc,s->mic_gate};try{dsp_control(features[row],!flags[row]);}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}}
  if(s->eq_view==3&&y>=453&&y<500)eq_default();
  if(s->eq_view==2&&y>=441&&y<490){if(x<850)codec_eq(!s->hw_eq);else eq_default();}
  if(!s->eq_view&&y>=411&&y<=461){if(x<800)s->temperature=std::max(50,s->temperature-1);else if(x>900)s->temperature=std::min(90,s->temperature+1);}
  if(y>=505){if(x<790){s->volume=std::max(0,s->volume-5);s->muted=0;}else if(x>912){s->volume=std::min(100,s->volume+5);s->muted=0;}else s->muted=!s->muted;try{waitok(spawn({"/usr/bin/amixer","-q","sset","Headphone",std::to_string(s->volume)+"%",s->muted?"mute":"unmute"}));}catch(...){} }
 }else if(!s->full&&x>=24&&x<674&&y>=524){
  bool video=kind(current)=="video"||kind(current)=="youtube"||kind(current)=="animation"||kind(current)=="audio";
  if(x<122){if(video&&(!strcmp(s->state,"ended")||!strcmp(s->state,"stopped"))){request({{"action","media.show"},{"params",current}});}else if(video&&worker>0){s->paused=!s->paused;if(s->decoder_pid>0)kill(s->decoder_pid,s->paused?SIGSTOP:SIGCONT);if(s->audio_pid>0)kill(s->audio_pid,s->paused?SIGSTOP:SIGCONT);if(s->audio_decoder_pid>0)kill(s->audio_decoder_pid,s->paused?SIGSTOP:SIGCONT);}else{s->zoom=1;s->panx=s->pany=0;}}
  else if(x<212)s->zoom=std::max(1.f,s->zoom-.5f);
  else if(x<302)s->zoom=std::min(4.f,s->zoom+.5f);else if(x<422&&video){eq_default();}else if(x<362&&!video)s->page=std::max(1,s->page-1);else if(x<422&&!video)s->page=std::min(10000,s->page+1);
  else if(x<588)s->full=1;
  else stop_display();
 }else if((x>=24&&x<674&&y>=124&&y<504)||s->full){double t=now();if(t-lasttap<.35){s->zoom=s->zoom>1?1:2;s->panx=s->pany=0;}lasttap=t;}
 s->version++;
}
static J touch_target(int startx,int starty,int x,int y,bool dragged,bool full){bool button=(full&&startx>=820&&starty<120)||(!full&&(startx>=704||(startx>=24&&startx<674&&starty>=524)));return {{"x",button?startx:x},{"y",button?starty:y},{"drag",button?false:dragged},{"button",button}};}
int main(int argc,char**argv){signal(SIGPIPE,SIG_IGN);s=(Shared*)mmap(nullptr,sizeof(Shared),PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANONYMOUS,-1,0);new(s)Shared();if(argc>1&&std::string(argv[1])=="--touch-target"){J q=J::parse(argv[2]);std::cout<<touch_target(q["start_x"],q["start_y"],q["x"],q["y"],q.value("drag",false),q.value("fullscreen",false)).dump()<<"\n";return 0;}if(argc>1&&std::string(argv[1])=="--classify"){std::cout<<kind(J::parse(argv[2]))<<"\n";return 0;}if(argc>1&&std::string(argv[1])=="--batch"){J out=J::array();for(auto p:J::parse(argv[2])){try{out.push_back(request(p));}catch(const std::exception&e){out.push_back({{"ok",false},{"error",e.what()}});}}std::cout<<out.dump()<<"\n";stop();return 0;}if(argc>1&&std::string(argv[1])=="--request"){try{std::cout<<request(J::parse(argv[2])).dump()<<"\n";}catch(const std::exception&e){std::cout<<J({{"ok",false},{"error",e.what()}}).dump()<<"\n";}stop();return 0;}if(argc>1)fbpath=argv[1];
 muse_audio::Codec device;codec=&device;if(device.available()){try{auto gains=device.gains();s->codec_available=1;for(int i=0;i<5;i++){s->hw_gain[i]=gains[i];if(gains[i])s->hw_eq=1;}s->limiter=device.get("DAC Limiter Switch");s->mic_hpf=device.get("High Pass Filter Switch");s->mic_alc=bool(device.get("ALC Enable Switch",true));s->mic_gate=device.get("ALC Noise Gate Switch");}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}}
 int server=socket(AF_INET,SOCK_STREAM|SOCK_CLOEXEC,0);int yes=1;setsockopt(server,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof(yes));sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(8765);a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(bind(server,(sockaddr*)&a,sizeof(a))||listen(server,8)){perror("listen");return 1;}
 int input=open("/dev/input/event0",O_RDONLY|O_NONBLOCK);input_absinfo ax{},ay{};if(input>=0){ioctl(input,EVIOCGABS(ABS_X),&ax);ioctl(input,EVIOCGABS(ABS_Y),&ay);}int rx=0,ry=0,down=0,last=0,px=0,py=0,startx=0,starty=0,slider=-1;bool dragged=false;double started=0;
 while(true){pollfd fds[2]={{server,POLLIN,0},{input,POLLIN,0}};poll(fds,2,100);if(worker>0&&waitpid(worker,nullptr,WNOHANG)==worker){kill(-worker,SIGTERM);worker=0;unlink("/tmp/muse-native-media.active");if(!strcmp(s->state,"ended")&&!pending.empty()){J next=pending.front();pending.pop_front();try{request({{"action","media.show"},{"params",next}});}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());state("error");}}}if(worker>0&&!strcmp(s->state,"ended")&&!pending.empty()){J next=pending.front();pending.pop_front();try{request({{"action","media.show"},{"params",next}});}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());state("error");}}if(fds[1].revents&POLLIN){input_event e{};while(read(input,&e,sizeof(e))==sizeof(e)){if(e.type==EV_ABS&&e.code==ABS_X)rx=e.value;if(e.type==EV_ABS&&e.code==ABS_Y)ry=e.value;if(e.type==EV_KEY&&e.code==BTN_TOUCH)down=e.value;if(e.type==EV_SYN&&e.code==SYN_REPORT){int x=(rx-ax.minimum)*1023/std::max(1,ax.maximum-ax.minimum),y=599-(ry-ay.minimum)*599/std::max(1,ay.maximum-ay.minimum);if(down&&!last){startx=px=x;starty=py=y;started=now();dragged=false;slider=eq_band(x,y);int hw=hw_band(x,y);if(hw>=0)slider=10+hw;if(slider>=10){try{hw_slider(slider-10,y);}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}}else if(slider>=0)eq_adjust(slider,y);}else if(down&&last){if(slider>=10){try{hw_slider(slider-10,y);}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}}else if(slider>=0)eq_adjust(slider,y);if(abs(x-startx)+abs(y-starty)>10)dragged=true;if(dragged&&startx<674&&starty>=124&&starty<504)touch(x,y,x-px,y-py,false,true,0);}else if(!down&&last&&slider<0){J target=touch_target(startx,starty,x,y,dragged,s->full);bool button=target["button"];fprintf(stderr,"touch %d,%d release %d,%d drag=%d button=%d\n",startx,starty,x,y,dragged,button);touch(target["x"],target["y"],0,0,true,target["drag"],button?0:now()-started);}px=x;py=y;last=down;}}}
 if(fds[0].revents&POLLIN){int c=accept4(server,nullptr,nullptr,SOCK_CLOEXEC);timeval timeout{2,0};setsockopt(c,SOL_SOCKET,SO_RCVTIMEO,&timeout,sizeof(timeout));std::string data;char buf[4096];J out;try{size_t header=std::string::npos,length=0;while(data.size()<280000){ssize_t n=read(c,buf,sizeof(buf));if(n<=0)throw std::runtime_error("incomplete HTTP request");data.append(buf,n);header=data.find("\r\n\r\n");if(header!=std::string::npos){auto lower=data.substr(0,header);std::transform(lower.begin(),lower.end(),lower.begin(),::tolower);auto pos=lower.find("content-length:");if(pos==std::string::npos)throw std::runtime_error("Content-Length required");length=std::stoul(lower.substr(pos+15));if(length>262144)throw std::runtime_error("request too large");if(data.size()>=header+4+length)break;}}if(header==std::string::npos||data.rfind("POST /media ",0)!=0)throw std::runtime_error("use POST /media");out=request(J::parse(data.substr(header+4,length)));}catch(const std::exception&e){out={{"ok",false},{"error",e.what()}};}std::string body=out.dump();std::string response="HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nConnection: close\r\nContent-Length: "+std::to_string(body.size())+"\r\n\r\n"+body;size_t done=0;while(done<response.size()){ssize_t n=write(c,response.data()+done,response.size()-done);if(n<=0)break;done+=n;}close(c);}}
}
