// SPDX-License-Identifier: Apache-2.0
// Board-native, bounded media renderer. No gateway process is used at runtime.
#include "vendor/json.hpp"
#include "audio_eq.hpp"
#include "codec_dsp.hpp"
#include "media_tabs.hpp"
#include "raster_cache.hpp"
#include "spoken_text.hpp"
#include "presentation_progress.hpp"
#include "board_media_client.hpp"
#include "media_sources.hpp"
#include "generative_ui.hpp"
#include <sys/stat.h>
#include <sys/syscall.h>
#define STB_IMAGE_IMPLEMENTATION
#define STBI_MAX_DIMENSIONS 8192
#include "vendor/stb_image.h"
#define STB_TRUETYPE_IMPLEMENTATION
#include "vendor/stb_truetype.h"
#include <linux/fb.h>
#include <linux/input.h>
#include <linux/videodev2.h>
#include <sys/socket.h>
#include <sys/mman.h>
#include <sys/wait.h>
#include <sys/ioctl.h>
#include <sys/resource.h>
#include <netinet/in.h>
#include <poll.h>
#include <fcntl.h>
#include <unistd.h>
#include <signal.h>
#include <cmath>
#include <fstream>
#include <iostream>
#include <chrono>
#include <algorithm>
#include <deque>
#include <thread>
#include <mutex>
#include <condition_variable>
using J=nlohmann::json;
static const std::string base=getenv("MUSE_MEDIA_BASE")?getenv("MUSE_MEDIA_BASE"):"/opt/muse-media/";
static const std::string cache_dir=getenv("MUSE_MEDIA_CACHE_DIR")?getenv("MUSE_MEDIA_CACHE_DIR"):"/tmp/muse-media-cache";
static MediaTabs tabs;static std::string requested_speech;
static volatile sig_atomic_t exiting=0;
struct RadioStation {const char* id;const char* name;const char* url;};
static const RadioStation radio_stations[]={
 {"paradise","Radio Paradise - Main","https://stream.radioparadise.com/mp3-128"},
 {"mellow","Radio Paradise - Mellow","https://stream.radioparadise.com/mellow-128"},
 {"rock","Radio Paradise - Rock","https://stream.radioparadise.com/rock-128"}};
static J radio_catalog(){J list=J::array();for(auto station:radio_stations)list.push_back({{"id",station.id},{"name",station.name},{"url",station.url}});return list;}
struct Shared {float zoom=1,panx=0,pany=0,position=0;int full=0,page=1,slide_interval_seconds=1,version=0,frames=0,paused=0,temperature=72,volume=75,muted=0,decoder_pid=0,audio_pid=0,audio_decoder_pid=0,eq_view=1,eq_version=0;int eq_gain[10]{},eq_level[10]{},hw_gain[5]{},sw_eq=1,hw_eq=0,limiter=0,mic_hpf=1,mic_alc=0,mic_gate=0,codec_available=0,spectrum_version=0,audio_running=0,audio_blocks=0;muse_ui::Progress progress;int speech_request=0,speech_phase=0;char speech_error[160]{};int document_revision=0,selected_block=-1,selected_point=-1;char document[280000]{};char state[24]="idle",error[160]="";};
static muse_audio::Codec* codec=nullptr;static Shared *s;static pid_t worker=0;static J current=J::object();static std::deque<J> pending;static std::string fbpath="/dev/fb0";
static double now(){return std::chrono::duration<double>(std::chrono::steady_clock::now().time_since_epoch()).count();}
static void state(const char *v){snprintf(s->state,sizeof(s->state),"%s",v);}
static bool exists(std::string p){return access(p.c_str(),X_OK)==0;}
static std::string readfile(std::string p,size_t limit){std::ifstream f(p,std::ios::binary);std::string v;char b[4096];while(f.read(b,sizeof(b))||f.gcount()){v.append(b,f.gcount());if(v.size()>limit)throw std::runtime_error("media exceeds size limit");}if(!f.eof())throw std::runtime_error("cannot read media");return v;}
static pid_t spawn(const std::vector<std::string>&args,int input=-1,int output=-1,int extra=-1,bool capture_error=false){pid_t p=fork();if(p==0){if(input>=0)dup2(input,0);else{int fd=open("/dev/null",O_RDONLY);dup2(fd,0);}if(output>=0)dup2(output,1);else{int fd=open("/dev/null",O_WRONLY);dup2(fd,1);}std::string log=args[0]==base+"curl"?"/tmp/muse-media-download-"+std::to_string(getppid())+".log":args[0]=="/usr/bin/aplay"?"/tmp/muse-media-audio.log":"/tmp/muse-media-backend.log";int fd=open(log.c_str(),O_CREAT|O_WRONLY|O_TRUNC,0600);dup2(capture_error&&output>=0?output:fd,2);if(extra>=0)dup2(extra,3);for(int i=extra>=0?4:3;i<1024;i++)close(i);std::vector<char*> av;for(auto&a:args)av.push_back(const_cast<char*>(a.c_str()));av.push_back(nullptr);execv(av[0],av.data());_exit(127);}if(p<0)throw std::runtime_error("cannot start backend");return p;}
static void waitok(pid_t p){int st=0;while(waitpid(p,&st,0)<0&&errno==EINTR){}if(!WIFEXITED(st)||WEXITSTATUS(st))throw std::runtime_error("media backend failed; see board backend log");}
struct DownloadError:std::runtime_error{int code;DownloadError(int value,const std::string& reason):std::runtime_error(reason),code(value){}};
static std::string fetch(std::string u,std::string cached="",size_t limit=8388608,int generation=0){if(!cached.empty()&&access(cached.c_str(),R_OK)==0)return cached;if(u.rfind("/opt/muse-media/assets/",0)==0||u.rfind(base+"assets/",0)==0)return u;if(u.rfind("https://",0)!=0)throw std::runtime_error("source must be HTTPS or a board asset path");std::string partial=cached.empty()?"/tmp/muse-media-source-"+std::to_string(getpid()):cached+".part-"+std::to_string(getpid());
 for(int attempt=0;attempt<3;attempt++){pid_t child=spawn({base+"curl","--fail","--location","--silent","--show-error","--user-agent","MuseGenUI/0.1 (MA35H0 media display)","--proto","=https","--proto-redir","=https","--max-time",getenv("MUSE_FETCH_TIMEOUT")?getenv("MUSE_FETCH_TIMEOUT"):"40","--max-filesize",std::to_string(limit),"--cacert",base+"ca-certificates.crt","-o",partial,u});int status=0;pid_t ended;do{ended=waitpid(child,&status,0);}while(ended<0&&errno==EINTR);if(ended<0)throw std::runtime_error("Cannot collect download result");int code=WIFEXITED(status)?WEXITSTATUS(status):128;if(!code){if(access(partial.c_str(),R_OK)!=0)throw std::runtime_error("Downloader returned success without a file");if(!cached.empty()){if(rename(partial.c_str(),cached.c_str()))throw std::runtime_error("cannot save cached media");return cached;}return partial;}
 unlink(partial.c_str());std::string log;try{log=readfile("/tmp/muse-media-download-"+std::to_string(getpid())+".log",4096);}catch(...){}int http=0;for(int value:{400,401,403,404,410,429,500,502,503,504})if(log.find(std::to_string(value))!=std::string::npos)http=value;bool transient=code==22&&(http==429||http>=500);if(transient&&attempt<2){if(generation>0)try{muse_board::call("media.progress",{{"operation","activity"},{"generation",generation},{"detail","Source HTTP "+std::to_string(http)+"; retry "+std::to_string(attempt+1)+"/2 in "+std::to_string(attempt+1)+"s"}});}catch(...){}usleep((attempt+1)*1000000);continue;}
 std::string reason=code==63?"Source exceeds download cache limit":code==22?"Source HTTP error"+(http?" "+std::to_string(http):std::string()):code==28?"Source download timed out":"Source download failed (curl "+std::to_string(code)+")";throw DownloadError(code,reason);}
 throw std::runtime_error("Source retries exhausted");}
static std::string image_input(const std::string& source,const std::string& cached,int generation=0){if(!cached.empty()&&cached.rfind(cache_dir+"/",0)==0&&access(cached.c_str(),R_OK)==0){int w=0,h=0,n=0;if(!stbi_info(cached.c_str(),&w,&h,&n)||w>4096||h>4096||int64_t(w)*h>4000000)unlink(cached.c_str());}return fetch(muse_media::image_source(source),cached,8388608,generation);}
static std::string video_input(const std::string& source,const std::string& cached,int generation=0){if(source.rfind("https://",0)!=0||cached.empty()||source.find(".m3u8")!=std::string::npos||source.find(".mpd")!=std::string::npos)return source;if(access(cached.c_str(),R_OK)==0)return cached;if(access((cached+".stream").c_str(),R_OK)==0)return source;try{return fetch(source,cached,64*1024*1024,generation);}catch(const DownloadError&e){if(e.code!=63)throw;std::ofstream marker(cached+".stream");marker<<"stream oversized video";return source;}}
static std::string youtube_source(const std::string& url,const std::string& cache){std::string path=cache+".resolved";struct stat st{};if(!cache.empty()&&stat(path.c_str(),&st)==0&&time(nullptr)-st.st_mtime<3600){try{return readfile(path,8192);}catch(...){}}std::string temp="/tmp/muse-resolved-"+std::to_string(getpid());int fd=open(temp.c_str(),O_CREAT|O_TRUNC|O_RDWR,0600);try{waitok(spawn({base+"youtube-resolve",url},-1,fd));}catch(...){close(fd);unlink(temp.c_str());throw;}close(fd);std::string result=readfile(temp,8192);unlink(temp.c_str());while(!result.empty()&&isspace(result.back()))result.pop_back();if(result.rfind("https://",0)!=0)throw std::runtime_error("YouTube resolver did not return HTTPS media");if(!cache.empty()){std::string pending=path+"-"+std::to_string(getpid());std::ofstream out(pending);out<<result;out.close();rename(pending.c_str(),path.c_str());}return result;}
static int eq_read(int* value){return __atomic_load_n(value,__ATOMIC_RELAXED);}
static void eq_write(int* value,int next){__atomic_store_n(value,next,__ATOMIC_RELAXED);}
static void pump_audio(int input,int output){
 setpriority(PRIO_PROCESS,syscall(SYS_gettid),-8);muse_audio::Equalizer eq;muse_audio::Spectrum spectrum;alignas(int16_t) unsigned char buffer[4100];size_t carry=0;
 while(true){ssize_t n=read(input,buffer+carry,4096);if(n<0&&errno==EINTR)continue;if(n<=0)break;size_t bytes=carry+n,whole=bytes-bytes%4;std::array<double,10> gains;for(int i=0;i<10;i++)gains[i]=(eq_read(&s->sw_eq)?eq_read(&s->eq_gain[i])/10.0:0);eq.configure(gains);eq.process(reinterpret_cast<int16_t*>(buffer),whole/4);eq_write(&s->audio_blocks,eq_read(&s->audio_blocks)+1);if(spectrum.process(reinterpret_cast<int16_t*>(buffer),whole/4)){for(int i=0;i<10;i++)eq_write(&s->eq_level[i],int(spectrum.levels()[i]*1000));eq_write(&s->spectrum_version,eq_read(&s->spectrum_version)+1);}size_t sent=0;while(sent<whole){ssize_t count=write(output,buffer+sent,whole-sent);if(count<0&&errno==EINTR)continue;if(count<=0){eq_write(&s->audio_running,0);close(input);close(output);return;}sent+=count;}carry=bytes-whole;memmove(buffer,buffer+whole,carry);}
 close(input);close(output);for(int i=0;i<10;i++)eq_write(&s->eq_level[i],0);eq_write(&s->spectrum_version,eq_read(&s->spectrum_version)+1);eq_write(&s->audio_running,0);
}
static int eq_band(int x,int y){if(s->full||s->eq_view!=1||x<704||x>=1000)return -1;int row=y>=329?1:0;int top=row?329:177;if(y<top-10||y>top+107)return -1;int column=std::clamp((x-704)/59,0,4);return row*5+column;}
static void eq_adjust(int band,int y){int top=band>=5?329:177;int gain=std::clamp(int(std::lround((top+45-y)*120.0/45.0)),-120,120);eq_write(&s->eq_gain[band],gain);s->eq_version++;s->version++;}
static std::array<int,5> hw_gains(){std::array<int,5> result;for(int i=0;i<5;i++)result[i]=s->hw_gain[i];return result;}
static void codec_eq(bool enabled){if(!codec||!codec->available())throw std::runtime_error("NAU8822 codec unavailable");codec->equalizer(hw_gains(),enabled);s->hw_eq=enabled;s->eq_version++;}
static void dsp_control(std::string feature,bool enabled){
 if(feature=="software_eq")eq_write(&s->sw_eq,enabled);
 else if(feature=="hardware_eq")codec_eq(enabled);
 else {const char* name=nullptr;int* flag=nullptr;bool enumeration=false;int value=enabled;
  if(feature=="limiter"){name="DAC Limiter Switch";flag=&s->limiter;}
  else if(feature=="mic_hpf"){name="High Pass Filter Switch";flag=&s->mic_hpf;}
  else if(feature=="mic_alc"){name="ALC Enable Switch";flag=&s->mic_alc;enumeration=true;value=enabled?3:0;}
  else if(feature=="mic_gate"){name="ALC Noise Gate Switch";flag=&s->mic_gate;}
  else throw std::runtime_error("unknown DSP feature");
  if(!codec||!codec->available())throw std::runtime_error("NAU8822 codec unavailable");codec->set(name,value,enumeration);*flag=enabled;
 }s->eq_version++;s->version++;
}
static void eq_default(){if(codec&&codec->available())codec->equalizer({},false);for(auto& gain:s->eq_gain)eq_write(&gain,0);for(auto& gain:s->hw_gain)gain=0;s->hw_eq=0;eq_write(&s->sw_eq,1);s->eq_version++;s->version++;}
static void hw_adjust(int band,int gain){if(band<0||band>=5||gain<-12||gain>12)throw std::runtime_error("hardware EQ band must be 0..4 and gain -12..12 dB");auto next=hw_gains();next[band]=gain;if(!codec||!codec->available())throw std::runtime_error("NAU8822 codec unavailable");codec->equalizer(next,s->hw_eq);s->hw_gain[band]=gain;s->eq_version++;s->version++;}
static void tune(J q){
 std::string preset=q.value("preset",std::string()),engine=q.value("engine",std::string("active"));
 double amount=q.value("amount_db",3.0);if(!std::isfinite(amount)||amount<0||amount>12)throw std::runtime_error("amount_db must be 0..12");
 if(engine=="active")engine=s->hw_eq&&!s->sw_eq?"hardware":"software";
 if(engine!="software"&&engine!="hardware")throw std::runtime_error("engine must be active, software or hardware");
 if(preset=="flat"){eq_default();return;}
 if(preset!="bass_up"&&preset!="bass_down"&&preset!="treble_up"&&preset!="treble_down"&&preset!="voice"&&preset!="music")throw std::runtime_error("unknown tone preset");
 bool hardware=engine=="hardware";int count=hardware?5:10;std::array<int,10> gains{};
 for(int i=0;i<count;i++)gains[i]=hardware?s->hw_gain[i]*10:eq_read(&s->eq_gain[i]);
 if(preset=="voice"||preset=="music"){
  const int voice_sw[]={-3,-3,-2,0,2,3,3,1,0,0},music_sw[]={3,3,2,0,-1,0,1,2,2,1};
  const int voice_hw[]={-3,-1,2,3,0},music_hw[]={3,1,0,2,2};
  for(int i=0;i<count;i++)gains[i]=10*(hardware?(preset=="voice"?voice_hw[i]:music_hw[i]):(preset=="voice"?voice_sw[i]:music_sw[i]));
 }else{bool bass=preset.find("bass")==0;int step=int(std::lround(amount*10))*(preset.find("down")!=std::string::npos?-1:1);for(int i=0;i<count;i++)if(bass?(i<(hardware?2:3)):(i>=(hardware?3:7)))gains[i]=std::clamp(gains[i]+step,-120,120);}
 if(hardware){auto next=hw_gains();for(int i=0;i<5;i++)next[i]=int(std::lround(gains[i]/10.0));if(!codec||!codec->available())throw std::runtime_error("NAU8822 codec unavailable");codec->equalizer(next,true);for(int i=0;i<5;i++)s->hw_gain[i]=next[i];s->hw_eq=1;}
 else {for(int i=0;i<10;i++)eq_write(&s->eq_gain[i],gains[i]);eq_write(&s->sw_eq,1);}
 s->eq_version++;s->version++;
}
static int hw_band(int x,int y){return !s->full&&s->eq_view==2&&x>=704&&x<999&&y>=212&&y<=372?(x-704)/59:-1;}
static void hw_slider(int band,int y){hw_adjust(band,std::clamp(int(std::lround((292-y)*12.0/70.0)),-12,12));}
struct BrandAsset {int width=0,height=0;std::vector<unsigned char> pixels;};
static std::map<std::string,BrandAsset> brand_assets;
static const BrandAsset* brand_asset(const char* name,int width,int height){
 std::string key=std::string(name)+"-"+std::to_string(width)+"x"+std::to_string(height);auto found=brand_assets.find(key);if(found!=brand_assets.end())return &found->second;
 int w,h,n;unsigned char* img=stbi_load((base+"assets/"+name).c_str(),&w,&h,&n,4);if(!img)return nullptr;float scale=std::min(float(width)/w,float(height)/h);BrandAsset item;item.width=std::max(1,int(w*scale));item.height=std::max(1,int(h*scale));item.pixels.resize(size_t(item.width)*item.height*4);for(int y=0;y<item.height;y++)for(int x=0;x<item.width;x++)memcpy(item.pixels.data()+(y*item.width+x)*4,img+((y*h/item.height)*w+x*w/item.width)*4,4);stbi_image_free(img);return &brand_assets.emplace(key,std::move(item)).first->second;
}
static void preload_brand_assets(){brand_asset("muse-logo.png",48,48);brand_asset("nuvoton-logo.png",150,22);brand_asset("winbond-logo.png",145,38);brand_asset("jollybot.png",56,56);brand_asset("athletics-logo.png",60,60);}
struct Renderer {
 int fd;unsigned char *fb;size_t bytes=4096*600,mapped=4096*600;fb_var_screeninfo screen{};bool flip=false;std::vector<unsigned char> composed=std::vector<unsigned char>(4096*600);std::string cachekey,media_type="text";std::vector<unsigned char> fonts;stbtt_fontinfo font{};bool hasfont=false;int clip_left=0,clip_top=0,clip_right=1024,clip_bottom=600;
 Renderer(){fd=open(fbpath.c_str(),O_RDWR);if(fd<0)throw std::runtime_error("framebuffer unavailable");if(fbpath=="/dev/fb0"){fb_var_screeninfo v{};fb_fix_screeninfo f{};if(ioctl(fd,FBIOGET_VSCREENINFO,&v)||ioctl(fd,FBIOGET_FSCREENINFO,&f)||v.xres!=1024||v.yres!=600||v.bits_per_pixel!=32||f.line_length!=4096)throw std::runtime_error("unsupported framebuffer geometry");screen=v;flip=getenv("MUSE_FB_PAGE_FLIP")&&v.yres_virtual>=1200&&f.smem_len>=bytes*2;if(flip)mapped=bytes*2;}fb=(unsigned char*)mmap(nullptr,mapped,PROT_READ|PROT_WRITE,MAP_SHARED,fd,0);if(fb==MAP_FAILED)throw std::runtime_error("cannot map framebuffer");try{auto data=readfile(base+"font.ttf",2000000);fonts.assign(data.begin(),data.end());hasfont=stbtt_InitFont(&font,fonts.data(),0);}catch(...){} }
 ~Renderer(){munmap(fb,mapped);close(fd);}
 void pixel(int x,int y,int r,int g,int b){if(x<clip_left||x>=clip_right||y<clip_top||y>=clip_bottom)return;size_t i=((599-y)*1024+1023-x)*4;composed[i]=b;composed[i+1]=g;composed[i+2]=r;composed[i+3]=255;}
 void rect(int x,int y,int w,int h,int r,int g,int b){int left=std::max(clip_left,x),right=std::min(clip_right,x+w),top=std::max(clip_top,y),bottom=std::min(clip_bottom,y+h);if(right<=left||bottom<=top)return;uint32_t color=0xff000000u|(r<<16)|(g<<8)|b;auto pixels=reinterpret_cast<uint32_t*>(composed.data());for(int j=top;j<bottom;j++)std::fill(pixels+(599-j)*1024+1024-right,pixels+(599-j)*1024+1024-left,color);}
 void text(std::string t,int x,int y,int size=20,int wrap=980,int color=0x253047){if(!hasfont)return;float scale=stbtt_ScaleForPixelHeight(&font,size);int start=x;for(unsigned char c:t){if(c=='\n'||x>wrap){x=start;y+=size+7;if(c=='\n')continue;}if(y>590)break;int w,h,dx,dy,advance;auto bitmap=stbtt_GetCodepointBitmap(&font,0,scale,c,&w,&h,&dx,&dy);for(int j=0;j<h;j++)for(int i=0;i<w;i++){int q=bitmap[j*w+i],px=x+dx+i,py=y+size+dy+j;if(q&&px>=0&&px<1024&&py>=0&&py<600){size_t offset=((599-py)*1024+1023-px)*4;pixel(px,py,(((color>>16)&255)*q+composed[offset+2]*(255-q))/255,(((color>>8)&255)*q+composed[offset+1]*(255-q))/255,((color&255)*q+composed[offset]*(255-q))/255);}}stbtt_FreeBitmap(bitmap,nullptr);stbtt_GetCodepointHMetrics(&font,c,&advance,nullptr);x+=int(advance*scale);}}
 void asset(const char* name,int x,int y,int width,int height){const auto* img=brand_asset(name,width,height);if(!img)return;x+=(width-img->width)/2;y+=(height-img->height)/2;for(int j=0;j<img->height;j++)for(int i=0;i<img->width;i++){const unsigned char* p=img->pixels.data()+(j*img->width+i)*4;int px=x+i,py=y+j;if(px<0||px>=1024||py<0||py>=600)continue;size_t offset=((599-py)*1024+1023-px)*4;int q=p[3];pixel(px,py,(p[0]*q+composed[offset+2]*(255-q))/255,(p[1]*q+composed[offset+1]*(255-q))/255,(p[2]*q+composed[offset]*(255-q))/255);}}
 void circle(int cx,int cy,int radius,int r,int g,int b){for(int y=-radius;y<=radius;y++)for(int x=-radius;x<=radius;x++)if(x*x+y*y<=radius*radius)pixel(cx+x,cy+y,r,g,b);}

 void line(int x0,int y0,int x1,int y1,int color){int dx=abs(x1-x0),sx=x0<x1?1:-1,dy=-abs(y1-y0),sy=y0<y1?1:-1,err=dx+dy;for(;;){pixel(x0,y0,color>>16,(color>>8)&255,color&255);if(x0==x1&&y0==y1)break;int e=2*err;if(e>=dy){err+=dy;x0+=sx;}if(e<=dx){err+=dx;y0+=sy;}}}
 void document(const J& doc){
  int vx=s->full?0:24,vy=s->full?0:124,vw=s->full?1024:650,vh=s->full?600:348;
  clip_left=vx;clip_top=vy;clip_right=vx+vw;clip_bottom=vy+vh;
  float z=s->zoom;int x=vx+int(s->panx),y=vy+int(s->pany),width=int((vw-24)*z);
  auto box=[&](int bx,int by,int bw,int bh,int color){rect(bx,by,bw,bh,color>>16,(color>>8)&255,color&255);};
  auto txt=[&](std::string value,int tx,int ty,int size=18,int color=0x253047,int end=0){text(value,tx,ty,int(size*z),end?end:x+width-8,color);};
  bool athletics=doc.value("theme",std::string())=="athletics";int accent=athletics?0x008964:0x5966ed;
  const int colors[]={accent,0xf2bf32,0x22b8cf,0xeb657e,0xa37bea,0xfb963d};
  box(x+8,y,width,int(76*z),athletics?0x003f2e:0x202a58);
  box(x+8,y+int(72*z),width,int(4*z),0xf2bf32);
  int title_x=x+20;
  if(doc.value("team_id",0)==133){int lx=x+int(16*z),ly=y+int(8*z),side=int(60*z);if(lx>=0&&ly>=0&&lx+side<=1024&&ly+side<=600)asset("athletics-logo.png",lx,ly,side,side);title_x=x+int(90*z);}
  txt(doc.value("title",std::string("Muse")),title_x,y+int(7*z),25,0xffffff);
  txt(doc.value("subtitle",std::string()),title_x,y+int(43*z),13,0xbee6df);
  y+=int(muse_ui::header_height(doc)*z);
  int block_index=0;
  for(const auto& b:doc["blocks"]){auto type=b.value("type",std::string());int height=muse_ui::block_height(b);
   int h=int(height*z);if(y+h<vy){y+=h+int(12*z);block_index++;continue;}if(y>=vy+vh)break;
   box(x+8,y,width,h,0xffffff);std::string title=b.value("title",b.value("label",std::string()));if(!title.empty())txt(title,x+20,y+10,18);
   if(type=="metrics"){int count=b["items"].size(),cw=width/count;for(int i=0;i<count;i++){int bx=x+8+i*cw;box(bx,y,cw-6,h,0x17283d);box(bx,y,cw-6,int(4*z),colors[i]);const auto& item=b["items"][i];txt(item.value("title",std::string()),bx+int(10*z),y+int(13*z),12,0xc8d6e7,bx+cw-10);txt(muse_ui::display(item["value"]),bx+int(10*z),y+int(35*z),29,colors[i],bx+cw-10);txt(item.value("unit",std::string()),bx+int(10*z),y+int(72*z),11,0xc8d6e7,bx+cw-10);}}
   else if(type=="metric"){txt(muse_ui::display(b["value"])+" "+b.value("unit",std::string()),x+20,y+34,34,accent);txt(b.value("detail",std::string()),x+20,y+76,14,0x68758a);}
   else if(type=="text")txt(b.value("text",std::string()),x+20,y+36,18);
   else if(type=="progress"){int bx=x+20,by=y+int(44*z),bw=width-28;box(bx,by,bw,int(16*z),0xe8effb);box(bx,by,int(bw*b["value"].get<double>()/b.value("max",100.0)),int(16*z),0x26ad99);txt(muse_ui::display(b["value"])+" / "+muse_ui::display(b.value("max",J(100)))+" "+b.value("unit",std::string()),bx,by+int(20*z),14);}
   else if(type=="table"){int n=b["columns"].size(),cw=(width-24)/n,by=y+int(38*z);for(int i=0;i<n;i++)txt(b["columns"][i],x+20+i*cw,by,14,0x68758a,x+20+(i+1)*cw-10);by+=int(30*z);for(const auto& row:b["rows"]){if(by>=vy+vh)break;for(int i=0;i<n;i++)txt(muse_ui::display(row[i]),x+20+i*cw,by,16,0x253047,x+20+(i+1)*cw-10);box(x+20,by+int(25*z),width-32,1,0xe8effb);by+=int(30*z);}}
   else {
    int count=b["labels"].size(),ns=b["series"].size(),px=x+int(68*z),py=y+int(60*z),pw=width-int(100*z),ph=int(145*z);double lo=0,hi=0;for(const auto& series:b["series"])for(const auto& v:series["values"]){lo=std::min(lo,v.get<double>());hi=std::max(hi,v.get<double>());}if(hi==lo)hi=lo+1;
    auto yy=[&](double v){return py+ph-int((v-lo)*ph/(hi-lo));};
    char val[32];for(int t=0;t<4;t++){double v=lo+(hi-lo)*t/3;int gy=yy(v);box(px,gy,pw,1,0xe8effb);snprintf(val,sizeof(val),"%.3g",v);txt(val,x+12,gy-int(9*z),12,0x68758a,px-6);}
    for(int j=0;j<ns;j++){const auto& series=b["series"][j];for(int i=0;i<count;i++){int cx=px+(2*i+1)*pw/(2*count),cy=yy(series["values"][i].get<double>());if(type=="bar"){int cell=std::max(1,pw/count),bw=std::max(1,cell/(ns+1));box(px+i*cell+j*bw,std::min(cy,yy(0)),bw-1,std::max(2,abs(cy-yy(0))),colors[j]);}else{if(i){int prevx=px+(2*i-1)*pw/(2*count);line(prevx,yy(series["values"][i-1].get<double>()),cx,cy,colors[j]);}circle(cx,cy,std::max(2,int(3*z)),colors[j]>>16,(colors[j]>>8)&255,colors[j]&255);}
     if(j==0&&i%std::max(1,(count+5)/6)==0)txt(b["labels"][i].get<std::string>().substr(0,10),cx-int(22*z),py+ph+int(8*z),12,0x68758a,cx+int(50*z));}
     txt(series.value("name",std::string("Series")),x+20+j*width/ns,y+int(226*z),12,colors[j],x+20+(j+1)*width/ns-8);
    }
    if(s->selected_block==block_index&&s->selected_point>=0&&s->selected_point<count){int i=s->selected_point;std::string detail=b["labels"][i];for(const auto& series:b["series"])detail+=" | "+series.value("name",std::string())+": "+muse_ui::display(series["values"][i]);box(x+12,y+int(214*z),width-8,int(25*z),0xe8effb);txt(detail,x+20,y+int(218*z),13);}
   }
   y+=h+int(12*z);block_index++;
  }
  if(!doc.value("source",std::string()).empty())txt("Source: "+doc["source"].get<std::string>(),x+12,y+4,13,0x68758a);
  clip_left=clip_top=0;clip_right=1024;clip_bottom=600;
  if(s->full){rect(840,0,184,88,232,239,251);text("Exit full",856,26,26);}
 }
 void media_bar(){
  const char* labels[]={"Text","Images","PDF","Video","Audio"};
  int active=media_type=="pdf"?2:media_type=="audio"?4:(media_type=="video"||media_type=="youtube"||media_type=="animation")?3:(media_type=="image"||media_type=="svg")?1:0;
  rect(0,64,1024,56,232,239,251);
  for(int i=0;i<5;i++){int x=24+i*196;bool selected=i==active;rect(x,66,184,52,selected?45:245,selected?108:247,selected?217:251);text(labels[i],x+(184-int(strlen(labels[i]))*11)/2,80,22,x+180,selected?0xffffff:0x253047);}
 }
 void chrome(std::string caption,bool video){
  std::string key=caption+std::to_string(s->full)+std::to_string(s->temperature)+std::to_string(s->volume)+std::to_string(s->muted)+std::to_string(video)+std::to_string(s->eq_view)+std::to_string(s->eq_version)+media_type+s->state+std::to_string(s->paused)+std::to_string(s->speech_phase);
  if(key==cachekey){rect(s->full?0:24,s->full?0:124,s->full?1024:650,s->full?600:348,245,247,251);return;}
  rect(0,0,1024,600,244,246,252);
  if(!s->full){
   rect(0,0,1024,64,255,255,255);asset("muse-logo.png",24,8,48,48);text("Muse",84,13,30);text("MA35H0 CPU + NAU8822 codec",208,5,23,610);text("Storage: Winbond W29N08GV",208,35,18,610,0x68758a);asset("nuvoton-logo.png",630,21,150,22);asset("winbond-logo.png",800,13,145,38);asset("jollybot.png",956,4,56,56);
   rect(24,112,650,403,255,255,255);text(caption.substr(0,180),38,caption.size()>65?474:478,caption.size()>65?12:17,660,0x68758a);
   rect(24,124,650,348,245,247,251);rect(688,112,316,480,255,255,255);
   const char* tabs[]={"Room","10 EQ","5 HW EQ","DSP"};for(int i=0;i<4;i++){rect(704+i*74,120,70,34,i==s->eq_view?232:245,i==s->eq_view?239:247,251);text(tabs[i],709+i*74,127,15,777+i*74);}
   if(s->eq_view==1){
    const char* labels[]={"31","63","125","250","500","1k","2k","4k","8k","16k"};
    for(int band=0;band<10;band++){int x=710+(band%5)*59,top=band>=5?329:177;rect(x+10,top,6,91,218,225,236);rect(x+2,top+45,36,1,184,196,213);int gain=eq_read(&s->eq_gain[band]);int handle=top+45-gain*45/120;rect(x+1,handle-7,31,14,45,108,217);text(labels[band],x,top+115,15,x+55);char value[20];snprintf(value,sizeof(value),"%+.1f",gain/10.0);text(value,x,top+96,14,x+55,0x68758a);}
    text(s->sw_eq?"CPU EQ ON | Spectrum before codec":"CPU EQ OFF | Spectrum before codec",709,464,15,998,0x68758a);
   }else if(s->eq_view==2){
    text("NAU8822 by Nuvoton",714,168,22);text(s->hw_eq?"ON - runs inside codec":"OFF - unity gain; settings retained",714,198,16,998,0x68758a);
    const char* labels[]={"105","300","850","2.4k","6.9k"};for(int i=0;i<5;i++){int x=710+i*59;rect(x+20,222,6,141,218,225,236);rect(x+1,292,49,1,184,196,213);rect(x+5,292-s->hw_gain[i]*70/12-7,36,14,45,108,217);text(labels[i],x,402,16,x+55);text(std::to_string(s->hw_gain[i])+"dB",x,377,15,x+55);}
    rect(708,441,138,44,232,239,251);text(s->hw_eq?"HW EQ: ON":"HW EQ: OFF",715,454,17);rect(852,441,144,44,232,239,251);text("EQ Default",866,454,17);
   }else if(s->eq_view==3){
    const char* names[]={"10-band CPU EQ","5-band codec EQ","Codec DAC limiter","Mic high-pass","Mic auto gain","Mic noise gate"};int flags[]={s->sw_eq,s->hw_eq,s->limiter,s->mic_hpf,s->mic_alc,s->mic_gate};
    for(int i=0;i<6;i++){int y=170+i*46;rect(708,y,288,40,245,247,251);text(names[i],717,y+10,18,919);rect(929,y+3,61,34,flags[i]?38:220,flags[i]?173:225,flags[i]?153:236);text(flags[i]?"ON":"OFF",942,y+11,16,994,flags[i]?0xffffff:0x253047);}
    rect(708,453,288,46,232,239,251);text("EQ Default (flat)",775,467,18);
   }else{
    text("Room 72 F  |  Heating",720,160,18,990,0x68758a);circle(852,290,115,205,212,223);circle(852,290,108,120,69,42);text(std::to_string(s->temperature),805,237,64,975,0xffffff);text("Target F",815,313,20,975,0xffffff);rect(725,411,67,50,232,239,251);rect(912,411,67,50,232,239,251);text("-",748,420,30);text("+",934,420,30);text("Heat mode",806,467,18,990,0x68758a);
   }
   rect(24,524,650,59,232,239,251);
   text(video?((!strcmp(s->state,"ended")||!strcmp(s->state,"stopped"))?"Replay":(s->paused?"Resume":"Pause")):"Fit",34,541,17);text("- Zoom",130,541,17);text("+ Zoom",220,541,17);if(video)text("EQ Default",307,541,17);else if(media_type=="text"){rect(304,529,120,49,45,108,217);text(s->speech_phase==1?"Preparing":s->speech_phase==2?"Reading":"Read to me",310,542,16,420,0xffffff);}else{text("<",322,541,20);text(">",382,541,20);}text("Full screen",450,541,17);text(media_type=="text"?"Stop voice":"Stop",media_type=="text"?592:610,541,15,670);
   text(s->muted?"Headphones muted":"Headphones "+std::to_string(s->volume)+"%",721,516,18);
   rect(704,550,296,42,232,239,251);text("-",730,553,26);text(s->muted?"Unmute":"Mute",809,558,18);text("+",956,553,26);
   media_bar();
  }else{rect(840,0,184,88,232,239,251);text("Exit full",856,26,26);}
  cachekey=key;
 }
 void spectrum_bars(){if(s->full||s->eq_view!=1)return;for(int band=0;band<10;band++){int x=750+(band%5)*59,top=band>=5?329:177;rect(x,top,11,91,235,240,249);int height=eq_read(&s->eq_level[band])*91/1000;rect(x,top+91-height,11,height,38,173,153);}rect(708,490,289,20,255,255,255);text(s->paused?"Spectrum paused":(eq_read(&s->audio_running)?"Spectrum LIVE":(!strcmp(s->state,"ended")?"Track ended - tap Replay":"No audio playing")),714,490,14,998,0x68758a);}
 void present(){
 if(s->progress.visible){rect(52,176,594,296,24,35,63);text("Getting your content ready",70,188,22,590,0xffffff);text("X",612,184,24,640,0xffffff);text(s->progress.topic,70,218,16,620,0xbdc9ef);int percent=s->progress.percent();text(std::to_string(percent)+"%",70,247,30,170,0x62dfc5);rect(172,261,348,14,52,67,100);rect(172,261,348*percent/100,14,98,223,197);text(std::to_string(s->progress.started>0?int(now()-s->progress.started):0)+"s",540,247,20,622,0xbdc9ef);const char* names[]={"Text","Images","PDF","Video"};const char* states[]={"Waiting","Loading","Ready","Error","No source"};for(int i=0;i<4;i++){text(names[i],70+i*140,290,18,208+i*140,0xffffff);text(states[s->progress.tabs[i]],70+i*140,315,16,208+i*140,s->progress.tabs[i]==3?0xff818f:0xbdc9ef);}const char* detail=s->progress.detail;for(int i=0;i<4;i++)if(s->progress.tabs[i]==3){detail=s->progress.errors[i];break;}text(detail,70,350,16,620,0xffffff);for(int i=0;i<3;i++)text(s->progress.history[i],70,398+i*20,13,620,0xbdc9ef);
 }

 if(flip){screen.yoffset=screen.yoffset?0:600;memcpy(fb+screen.yoffset*4096,composed.data(),bytes);screen.activate=FB_ACTIVATE_VBL;if(ioctl(fd,FBIOPAN_DISPLAY,&screen)){flip=false;memcpy(fb,composed.data(),bytes);}}else memcpy(fb,composed.data(),bytes);}
 void image(const unsigned char*rgb,int w,int h,std::string caption,bool video=false){chrome(caption,video);int vx=s->full?0:24,top=s->full?0:124,vw=s->full?1024:650,vh=s->full?600:348;float scale=std::min(float(vw)/w,float(vh)/h)*s->zoom;if(video&&!s->full)scale=std::min(scale,1.15f*s->zoom);s->panx=std::clamp(s->panx,-std::max(0.f,(w*scale-vw)/2),std::max(0.f,(w*scale-vw)/2));s->pany=std::clamp(s->pany,-std::max(0.f,(h*scale-vh)/2),std::max(0.f,(h*scale-vh)/2));float left=vx+(vw-w*scale)/2+s->panx,up=top+(vh-h*scale)/2+s->pany;int x0=std::max(vx,int(std::ceil(left))),x1=std::min(vx+vw,int(std::ceil(left+w*scale))),y0=std::max(top,int(std::ceil(up))),y1=std::min(top+vh,int(std::ceil(up+h*scale)));int samples[1024];for(int x=x0;x<x1;x++)samples[x]=std::clamp(int((x-left)/scale),0,w-1);for(int y=y0;y<y1;y++){int sy=std::clamp(int((y-up)/scale),0,h-1);for(int x=x0;x<x1;x++){const unsigned char*p=rgb+(sy*w+samples[x])*3;pixel(x,y,p[0],p[1],p[2]);}}if(s->full){rect(840,0,184,88,232,239,251);text("Exit full",856,26,26);}spectrum_bars();present();s->frames++;}
};
static std::string kind(J p){std::string k=p.value("kind","auto"),u=p.value("url","");if(k!="auto")return k;auto end=u.find('?');std::string path=u.substr(0,end);std::transform(path.begin(),path.end(),path.begin(),::tolower);if(u.find("youtu.be/")!=std::string::npos||u.find("youtube.com/")!=std::string::npos)return "youtube";auto dot=path.rfind('.');std::string ext=dot==std::string::npos?"":path.substr(dot+1);if(ext=="pdf")return "pdf";if(ext=="svg")return "svg";if(ext=="gif")return "animation";for(auto e:{"png","jpg","jpeg","webp","bmp","tga","psd","hdr","pnm"})if(ext==e)return "image";for(auto e:{"mp3","wav","flac","ogg","opus","aac","m4a"})if(ext==e)return "audio";for(auto e:{"mp4","webm","mkv","mov","avi","m3u8","mpd","ts","flv"})if(ext==e)return "video";if(p.contains("slides"))return "image";if(p.contains("text")||p.contains("ui"))return "text";for(auto e:{"txt","md","json","csv","log","html","htm"})if(ext==e)return "text";return "unknown";}
struct VC8KPP {int enable_pp,frame_buf_paddr,frame_buff_size,frame_buf_w,frame_buf_h,img_out_x,img_out_y,img_out_w,img_out_h,img_out_fmt,rotation,pp_out_dst,libjpeg_mode,reserved[8];};
static bool configure_decoder(){int fd=open("/dev/video0",O_RDWR);if(fd<0)return false;VC8KPP pp{};pp.frame_buf_w=1024;pp.frame_buf_h=600;pp.img_out_w=640;pp.img_out_h=360;pp.img_out_fmt=V4L2_PIX_FMT_NV12;bool ok=ioctl(fd,_IOW('v',91,VC8KPP),&pp)>=0;close(fd);return ok;}
static void play(J p){
 try {signal(SIGTERM,SIG_DFL);signal(SIGINT,SIG_DFL);setpgid(0,0);for(int fd=3;fd<1024;fd++)close(fd);struct rlimit mem{128*1024*1024,128*1024*1024},fs{65*1024*1024,65*1024*1024};setrlimit(RLIMIT_AS,&mem);setrlimit(RLIMIT_FSIZE,&fs);struct rlimit stack{1024*1024,1024*1024};setrlimit(RLIMIT_STACK,&stack);int active=open("/tmp/muse-native-media.active",O_CREAT|O_WRONLY,0600);if(active>=0)close(active);state("loading");std::string k=kind(p),u=p.value("url",""),caption=p.value("caption","Muse media");Renderer r;r.media_type=k;if(k!="text"&&!p.value("_empty",false)){r.chrome(caption,k=="video"||k=="youtube"||k=="audio"||k=="animation");r.text("Loading "+k+"...",40,155,24,660);r.present();}
 if(k=="text"||p.value("_empty",false)){std::string txt=p.contains("text")?p["text"].get<std::string>():readfile(fetch(u,p.value("_cache_file",std::string())),256*1024);state(p.value("_state",std::string("ready")).c_str());int last=-1;while(true){if(last!=s->version){r.chrome(caption,p.value("_controls",false));int revision=eq_read(&s->document_revision);if(!(revision&1)){std::string snapshot=(p.value("_controls",false)||p.value("_empty",false))?p.dump():std::string(s->document);__atomic_thread_fence(__ATOMIC_ACQUIRE);if(revision==eq_read(&s->document_revision)&&!snapshot.empty()){try{J live=J::parse(snapshot);if(live.contains("ui"))r.document(live["ui"]);else{r.clip_left=s->full?0:24;r.clip_top=s->full?0:124;r.clip_right=s->full?1024:674;r.clip_bottom=s->full?600:472;r.text(live.value("text",txt),(s->full?0:24)+int(s->panx),(s->full?0:124)+int(s->pany),int(20*s->zoom),s->full?1000:660);r.clip_left=r.clip_top=0;r.clip_right=1024;r.clip_bottom=600;}}catch(...){} }}last=s->version;r.present();s->frames++;}usleep(25000);}}
 if(k=="image"||k=="pdf"||k=="svg") {
  bool slideshow=p.contains("slides")&&!p["slides"].empty();int last=-1,prevpage=-1,w=0,h=0,n=0;unsigned char* decoded=nullptr;const unsigned char* img=nullptr;muse_media::RasterCache pixels;double changed=now();state("loading");
  while(true){if(slideshow&&s->page>int(p["slides"].size()))s->page=1;
   if(prevpage!=s->page){if(decoded){stbi_image_free(decoded);decoded=nullptr;}pixels.clear();std::string cache=p.value("_cache_file",std::string());if(slideshow)cache+="-"+std::to_string(s->page);std::string raw=cache.empty()?std::string():cache+(k=="image"?".rgb":".page-"+std::to_string(s->page)+".rgb");
    if(pixels.open(raw)){w=pixels.width;h=pixels.height;img=pixels.pixels();}
    else {std::string source=slideshow?p["slides"][s->page-1].at("url").get<std::string>():u;std::string path=(k=="image"?image_input(source,cache):fetch(source,cache)),raster=path;
     if(k!="image"){std::string pagefile="/tmp/muse-media-page-"+std::to_string(getpid())+".png";waitok(spawn({base+"mutool","draw","-q","-F","png","-w","1400","-h","1400","-o",pagefile,path,std::to_string(s->page)}));raster=pagefile;}
     if(!stbi_info(raster.c_str(),&w,&h,&n)||w>4096||h>4096||int64_t(w)*h>4000000)throw std::runtime_error("image too large or unsupported");decoded=stbi_load(raster.c_str(),&w,&h,&n,3);if(!decoded)throw std::runtime_error("image decode failed");muse_media::RasterCache::write(raw,w,h,decoded);img=decoded;
    }
    prevpage=s->page;last=-1;changed=now();state("ready");
   }
   if(last!=s->version){std::string label=caption;if(slideshow)label=p["slides"][s->page-1].value("caption",caption)+" | "+std::to_string(s->page)+"/"+std::to_string(p["slides"].size());else if(k!="image")label+=" | page "+std::to_string(s->page);r.image(img,w,h,label);last=s->version;}
   if(slideshow&&!s->paused&&now()-changed>=s->slide_interval_seconds){s->page=s->page%p["slides"].size()+1;s->version++;}usleep(25000);
  }
 }

 if(k=="youtube"&&p.contains("_cache_file")&&access(p["_cache_file"].get<std::string>().c_str(),R_OK)==0){u=p["_cache_file"];k="video";}
 if(k=="youtube"){if(!exists(base+"youtube-resolve"))throw std::runtime_error("YouTube resolver unavailable");u=youtube_source(u,p.value("_cache_file",std::string()));k="video";}
 if(k=="video"||k=="audio"||k=="animation"){
  float starting_position=p.value("live",false)?0:s->position;if(p.value("live",false))s->position=0;std::string input=u;if(input.rfind("https://",0)!=0&&input.rfind("/opt/muse-media/assets/",0)!=0&&input.rfind(base+"assets/",0)!=0&&input.rfind(cache_dir+"/",0)!=0)throw std::runtime_error("HTTPS media or a board asset required");
  if(!p.value("live",false)&&!p.value("stream",false)&&input.rfind("https://",0)==0&&!p.value("_cache_file",std::string()).empty()&&input.find(".m3u8")==std::string::npos&&input.find(".mpd")==std::string::npos)input=video_input(input,p["_cache_file"]);
  std::string metadata;
  std::string metadata_cache=p.value("_cache_file",std::string())+".metadata";
  if(k=="video"&&access(metadata_cache.c_str(),R_OK)==0)metadata=readfile(metadata_cache,16384);
  if(k=="video"&&metadata.empty()){int probe[2];if(pipe(probe))throw std::runtime_error("cannot create probe pipe");std::vector<std::string> probe_args{base+"ffmpeg","-nostdin","-hide_banner","-rw_timeout","15000000"};if(input.rfind("https://",0)==0)probe_args.insert(probe_args.end(),{"-tls_verify","1","-ca_file",base+"ca-certificates.crt"});probe_args.insert(probe_args.end(),{"-i",input});pid_t pp=spawn(probe_args,-1,probe[1],-1,true);close(probe[1]);char buf[1024];ssize_t n;while((n=read(probe[0],buf,sizeof(buf)))>0){if(metadata.size()<16384)metadata.append(buf,n);}close(probe[0]);waitpid(pp,nullptr,0);if(!metadata.empty()){std::ofstream file(metadata_cache);file<<metadata;}}
  bool hardware=false&&k=="video"&&metadata.find("Video: h264")!=std::string::npos&&configure_decoder();
  std::vector<std::string> args{base+"ffmpeg","-nostdin","-v","info","-threads","1","-filter_threads","1","-filter_complex_threads","1","-rw_timeout","15000000"};if(input.rfind("https://",0)==0)args.insert(args.end(),{"-tls_verify","1","-ca_file",base+"ca-certificates.crt"});if(k=="animation")args.insert(args.end(),{"-stream_loop","-1"});if(hardware)args.insert(args.end(),{"-c:v","h264_v4l2m2m","-num_output_buffers","4","-num_capture_buffers","6"});if(s->position>0)args.insert(args.end(),{"-ss",std::to_string(s->position)});args.insert(args.end(),{"-re","-i",input});
  int audiofd[2]={-1,-1},pcmfd[2]={-1,-1};std::thread audio_pump;pid_t player=0,audio_decoder=0;bool audio=k=="video"&&p.value("audio",true)&&metadata.find("Audio:")!=std::string::npos;
  std::vector<unsigned char> last_frame;int pipefd[2];if(pipe(pipefd))throw std::runtime_error("cannot create decoder pipe");if(k=="audio")args.insert(args.end(),{"-vn","-threads","1","-f","s16le","-ac","2","-ar","48000","pipe:1"});else args.insert(args.end(),{"-an","-vf","scale=480:270:force_original_aspect_ratio=decrease,pad=480:270:(ow-iw)/2:(oh-ih)/2,fps=20","-pix_fmt","rgb24","-threads","1","-f","rawvideo","pipe:1"});
  if(audio||k=="audio"){eq_write(&s->audio_running,1);muse_board::call("media.speech",{{"operation","stop"}});bool available=false;for(int attempt=0;attempt<40;attempt++){std::ifstream pcm("/proc/asound/card0/pcm0p/sub0/status");std::string status((std::istreambuf_iterator<char>(pcm)),{});if(status.empty()||status.find("closed")!=std::string::npos){available=true;break;}usleep(50000);}if(!available){eq_write(&s->audio_running,0);throw std::runtime_error("Headphone output is busy; speech did not release it");}if(pipe(pcmfd))throw std::runtime_error("cannot create EQ pipe");if(audio&&pipe(audiofd))throw std::runtime_error("cannot create audio pipe");player=spawn({"/usr/bin/aplay","-q","--buffer-size=8192","--period-size=1024","-D","hw:0,0","-t","raw","-f","S16_LE","-c","2","-r","48000"},pcmfd[0]);close(pcmfd[0]);
   if(audio){std::vector<std::string> audio_args{base+"ffmpeg","-nostdin","-v","error","-threads","1","-filter_threads","1","-rw_timeout","15000000"};if(input.rfind("https://",0)==0)audio_args.insert(audio_args.end(),{"-tls_verify","1","-ca_file",base+"ca-certificates.crt"});if(s->position>0)audio_args.insert(audio_args.end(),{"-ss",std::to_string(s->position)});audio_args.insert(audio_args.end(),{"-i",input,"-vn","-threads","1","-f","s16le","-ac","2","-ar","48000","pipe:1"});audio_decoder=spawn(audio_args,-1,audiofd[1]);close(audiofd[1]);s->audio_decoder_pid=audio_decoder;setpriority(PRIO_PROCESS,audio_decoder,-5);setpriority(PRIO_PROCESS,player,-10);}}
  pid_t decoder=spawn(args,-1,pipefd[1]);s->decoder_pid=decoder;s->audio_pid=player;close(pipefd[1]);if(audio||k=="audio"){eq_write(&s->audio_running,1);audio_pump=std::thread(pump_audio,audio?audiofd[0]:pipefd[0],pcmfd[1]);}state("playing");if(k=="audio"){while(eq_read(&s->audio_running)){s->position=starting_position+eq_read(&s->audio_blocks)*1024.f/48000;r.chrome(caption,true);r.text(p.value("live",false)?"Live radio through headphones":"Audio playing through headphones",40,155,25,665);r.text(caption,40,190,18,660,0x68758a);for(int i=0;i<3;i++){r.rect(40,235+i*60,610,48,232,239,251);r.text(radio_stations[i].name,56,248+i*60,20,640);}r.text("Choose a station above",40,433,16,660,0x68758a);r.spectrum_bars();r.present();s->frames++;usleep(80000);}audio_pump.join();waitok(player);}else{
   std::mutex lock;std::condition_variable changed;std::vector<unsigned char> latest(480*270*3);bool finished=false,truncated=false;unsigned sequence=0;
   std::thread reader([&]{std::vector<unsigned char> next(latest.size());while(true){size_t used=0;while(used<next.size()){ssize_t count=read(pipefd[0],next.data()+used,next.size()-used);if(count<=0)break;used+=count;}if(used!=next.size()){std::lock_guard<std::mutex> guard(lock);finished=true;truncated=used!=0;changed.notify_one();break;}{std::lock_guard<std::mutex> guard(lock);next.swap(latest);sequence++;}changed.notify_one();}});
   unsigned shown=0;int view=-1,meter=-1;double presented=0;std::vector<unsigned char> frame(latest.size());while(true){std::unique_lock<std::mutex> guard(lock);changed.wait_for(guard,std::chrono::milliseconds(50),[&]{return shown!=sequence||view!=s->version||meter!=eq_read(&s->spectrum_version)||(finished&&!eq_read(&s->audio_running));});bool fresh=shown!=sequence;if(fresh){frame=latest;shown=sequence;s->position=starting_position+sequence/20.f;}bool done=finished;if((fresh||view!=s->version||meter!=eq_read(&s->spectrum_version))&&shown){view=s->version;meter=eq_read(&s->spectrum_version);guard.unlock();double delay=.05-(now()-presented);if(delay>0)usleep(int(delay*1000000));r.image(frame.data(),480,270,caption,true);presented=now();}else guard.unlock();if(done&&!eq_read(&s->audio_running))break;}
   reader.join();if(truncated)throw std::runtime_error("truncated video frame");last_frame=std::move(frame);close(pipefd[0]);}
  waitok(decoder);if(audio){audio_pump.join();waitok(audio_decoder);waitok(player);}s->decoder_pid=s->audio_pid=s->audio_decoder_pid=0;s->version++;state("ended");int last=-1;while(true){if(last!=s->version){if(!last_frame.empty())r.image(last_frame.data(),480,270,caption,true);else{r.chrome(caption,true);r.spectrum_bars();r.text("Playback finished - tap Replay",40,160,28);r.present();}last=s->version;}usleep(25000);}
 }
 throw std::runtime_error("unsupported media type; query media.capabilities");
 }catch(const std::exception& e){snprintf(s->error,sizeof(s->error),"%s",e.what());state("error");try{Renderer error_view;error_view.media_type=kind(p);int revision=-1;while(true){if(revision!=s->version){error_view.chrome(p.value("caption",std::string("Muse media")),false);error_view.text("Source could not load",40,155,26,660,0xc93c59);error_view.text(s->error,40,200,18,660,0x68758a);error_view.text("You can still switch tabs or retry this source.",40,260,17,660);error_view.present();revision=s->version;}usleep(25000);}}catch(...){_exit(1);}}
}
static void stop(){if(worker>0){kill(-worker,SIGCONT);kill(-worker,SIGTERM);for(int i=0;i<20;i++){if(waitpid(worker,nullptr,WNOHANG)==worker){worker=0;break;}usleep(10000);}if(worker){kill(-worker,SIGKILL);waitpid(worker,nullptr,0);worker=0;}}unlink("/tmp/muse-native-media.active");s->decoder_pid=s->audio_pid=s->audio_decoder_pid=0;eq_write(&s->audio_running,0);for(auto& level:s->eq_level)eq_write(&level,0);s->paused=0;state("stopped");}
static void stop_display(){stop();s->full=0;s->version++;worker=fork();if(worker==0){play({{"kind","text"},{"text","Playback stopped. Tap Replay to start again."},{"caption",current.value("caption",std::string("Muse media"))},{"_state","stopped"},{"_controls",true}});_exit(0);}if(worker<0)throw std::runtime_error("cannot start display worker");setpgid(worker,worker);}
static J capabilities(){return {{"equalizer",{{"software_bands",10},{"codec","NAU8822"},{"hardware_bands",5},{"hardware_hz",{105,300,850,2400,6900}},{"gain_db",{-12,12}},{"hardware_off","unity gain; settings retained"},{"spectrum_tap","PCM before codec DSP"},{"switches",{"software_eq","hardware_eq","limiter","mic_hpf","mic_alc","mic_gate"}}}},{"runtime","board-native"},{"internet","board Ethernet via ICS; no laptop media process"},{"image",{"PNG","JPEG","WebP","BMP","TGA","PSD","HDR","PNM"}},{"text",{"plain text","Markdown as text","JSON as text","CSV as text","live generated UI: metric, bar, line, table, progress"}},{"video_backend",exists(base+"ffmpeg")},{"h264_hardware_device",access("/dev/video0",F_OK)==0},{"gpu_device",access("/dev/galcore",F_OK)==0},{"video",{"MP4/H.264","WebM/VP8/VP9","MKV","MOV","AVI","MPEG-TS","HLS"}},{"audio",{"PCM/WAV","MP3","AAC/M4A","FLAC","Ogg/Vorbis","Opus"}},{"pdf",exists(base+"mutool")},{"svg",exists(base+"mutool")},{"animation",exists(base+"ffmpeg")},{"youtube_watch_urls",exists(base+"youtube-resolve")},{"pinch",false},{"touch",{"drag pan/scroll","zoom buttons","full screen toggle"}},{"limits",{{"download_bytes",8388608},{"video_resolution","480x270"},{"video_fps",20},{"video_audio",true},{"drm",false}}}};}
static void publish_text(const J& q){std::string data=q.dump();if(data.size()>=sizeof(s->document))throw std::runtime_error("text document too large");__atomic_add_fetch(&s->document_revision,1,__ATOMIC_ACQ_REL);memcpy(s->document,data.c_str(),data.size()+1);__atomic_add_fetch(&s->document_revision,1,__ATOMIC_RELEASE);s->version++;}
static void persist_tabs(){std::string path=cache_dir+"/tabs.json",temp=path+".new";{std::ofstream index(temp);index<<J(tabs.last).dump();if(!index)throw std::runtime_error("cannot save tab cache");}if(rename(temp.c_str(),path.c_str()))throw std::runtime_error("cannot commit tab cache");}
static J request(J p,bool restore=false){std::string action=p.value("action","");
 if(action=="audio.stations")return {{"ok",true},{"payload",radio_catalog()}};
 if(action=="audio.radio"){std::string id=p.value("params",J::object()).value("station",std::string("paradise"));for(auto station:radio_stations)if(id==station.id)return request({{"action","media.show"},{"params",{{"kind","audio"},{"url",station.url},{"caption",station.name},{"live",true}}}});throw std::runtime_error("unknown radio station");}
if(action=="audio.tune"){tune(p.value("params",J::object()));J result=request({{"action","media.status"}});result["payload"]["preset"]=p["params"].value("preset",std::string());return result;}if(action=="media.capabilities")return {{"ok",true},{"payload",capabilities()}};if(action=="media.status")return {{"ok",true},{"payload",{{"state",s->state},{"error",s->error},{"frames",s->frames},{"queued",pending.size()},{"media_kind",current.empty()?"none":kind(current)},{"generative_ui",current.contains("ui")},{"selected_point",s->selected_point},{"worker_pid",worker},{"live",current.value("live",false)},{"tabs",tabs.status()},{"zoom",s->zoom},{"position_seconds",s->position},{"slideshow_interval_seconds",s->slide_interval_seconds},{"page",s->page},{"fullscreen",bool(s->full)},{"paused",bool(s->paused)},{"temperature_f",s->temperature},{"volume_percent",s->volume},{"muted",bool(s->muted)},{"equalizer_db",J::array({eq_read(&s->eq_gain[0])/10.0,eq_read(&s->eq_gain[1])/10.0,eq_read(&s->eq_gain[2])/10.0,eq_read(&s->eq_gain[3])/10.0,eq_read(&s->eq_gain[4])/10.0,eq_read(&s->eq_gain[5])/10.0,eq_read(&s->eq_gain[6])/10.0,eq_read(&s->eq_gain[7])/10.0,eq_read(&s->eq_gain[8])/10.0,eq_read(&s->eq_gain[9])/10.0})},{"software_eq_enabled",bool(s->sw_eq)},{"hardware_eq_enabled",bool(s->hw_eq)},{"hardware_eq_db",J::array({s->hw_gain[0],s->hw_gain[1],s->hw_gain[2],s->hw_gain[3],s->hw_gain[4]})},{"dsp",{{"available",bool(s->codec_available)},{"limiter",bool(s->limiter)},{"mic_hpf",bool(s->mic_hpf)},{"mic_alc",bool(s->mic_alc)},{"mic_gate",bool(s->mic_gate)}}},{"readiness",s->progress.status()},{"speech",{{"phase",s->speech_phase},{"error",s->speech_error}}},{"audio_running",bool(eq_read(&s->audio_running))},{"audio_blocks",eq_read(&s->audio_blocks)},{"spectrum_updates",eq_read(&s->spectrum_version)},{"spectrum",J::array({eq_read(&s->eq_level[0]),eq_read(&s->eq_level[1]),eq_read(&s->eq_level[2]),eq_read(&s->eq_level[3]),eq_read(&s->eq_level[4]),eq_read(&s->eq_level[5]),eq_read(&s->eq_level[6]),eq_read(&s->eq_level[7]),eq_read(&s->eq_level[8]),eq_read(&s->eq_level[9])})}}}};
 if(action=="media.progress"){J q=p.value("params",J::object());auto op=q.value("operation",std::string());if(op=="begin")s->progress.begin(q.value("topic",std::string("New presentation")));else if(op=="dismiss")s->progress.visible=0;else if(op=="update"){if(q.value("generation",-1)!=s->progress.generation)return {{"ok",false},{"error","presentation replaced"}};int index=q.value("index",-1),value=q.value("state",-1);if(index<0||index>=4||value<0||value>4)throw std::runtime_error("invalid readiness state");s->progress.tabs[index]=value;snprintf(s->progress.errors[index],160,"%s",value==3?q.value("detail",std::string("Source failed")).c_str():"");s->progress.activity(q.value("detail",std::string()));if(s->progress.percent()==100)s->progress.hide_at=now()+3;}else if(op=="activity"){if(q.contains("generation")&&q["generation"]!=s->progress.generation)return {{"ok",false},{"error","presentation replaced"}};s->progress.activity(q.value("detail",std::string()));}else if(op!="status")throw std::runtime_error("unknown progress operation");if(op!="status")s->version++;return {{"ok",true},{"payload",s->progress.status()}};}
 if(action=="media.enqueue"){J q=p.value("params",J::object());if(!q.is_object()||pending.size()>=8)throw std::runtime_error("invalid media or queue full");pending.push_back(q);return {{"ok",true},{"payload",{{"queued",pending.size()}}}};}
 if(action=="media.speech"){J q=p.value("params",J::object());auto operation=q.value("operation",std::string());if(operation=="read"){requested_speech=muse_ui::spoken_text(tabs.last[0]);if(requested_speech.empty())throw std::runtime_error("Text tab is empty");s->speech_request=1;s->speech_phase=1;s->speech_error[0]=0;s->version++;return {{"ok",true},{"payload",{{"queued",true},{"characters",requested_speech.size()}}}};}if(operation=="stop"){s->speech_request=2;s->speech_phase=0;s->speech_error[0]=0;s->version++;return {{"ok",true}};}if(operation=="poll"){J payload={{"request",s->speech_request}};if(s->speech_request==1)payload["text"]=requested_speech;s->speech_request=0;return {{"ok",true},{"payload",payload}};}if(operation=="state"){int phase=q.value("phase",0);if(phase<0||phase>3)throw std::runtime_error("invalid speech state");if(phase!=s->speech_phase){s->speech_phase=phase;s->version++;}snprintf(s->speech_error,sizeof(s->speech_error),"%s",q.value("error",std::string()).c_str());return {{"ok",true}};}throw std::runtime_error("unknown speech operation");}
 if(action=="media.context"){
  J q=p.at("params");muse_ui::presentation_validate(q);std::string title=q["document"].value("title",std::string("Muse"));bool same_topic=tabs.last[0].is_object()&&tabs.last[0].contains("ui")&&muse_ui::same_topic(tabs.last[0]["ui"],q["document"]);bool same_document=same_topic&&tabs.last[0]["ui"]==q["document"];int desired=same_topic&&tabs.active>=0&&tabs.active<4?tabs.active:0;bool incomplete=q.value("pending_media",false);
  if(tabs.active>=0&&!current.empty()){current["_position"]=s->position;current["_zoom"]=s->zoom;current["_panx"]=s->panx;current["_pany"]=s->pany;current["page"]=s->page;tabs.last[tabs.active]=current;}
  int prior_ready[4];for(int i=0;i<4;i++)prior_ready[i]=s->progress.tabs[i];bool retained[4]{};
  std::array<J,4> next;next[0]={{"kind","text"},{"text",""},{"ui",q["document"]},{"caption",title}};
  for(int i=1;i<4;i++)next[i]={{"kind",media_category_name(i)},{"text","No "+std::string(media_category_name(i))+" source supplied for "+title+"."},{"caption",title},{"_empty",true},{"_pending",incomplete}};
  if(q.contains("slides")&&!q["slides"].empty())next[1]={{"kind","image"},{"slides",q["slides"]},{"caption",title+" photos"},{"interval_seconds",q.value("interval_seconds",1)}};
  if(q.contains("pdf_url")){std::string url=q["pdf_url"];if(url.rfind(base+"assets/",0)!=0&&url.rfind("https://",0)!=0)throw std::runtime_error("invalid generated report path");next[2]={{"kind","pdf"},{"url",url},{"caption",title+" report"}};}
  if(q.contains("video")){std::string url=q["video"].value("url",std::string());if(url.rfind("https://",0)!=0&&url.rfind(base+"assets/",0)!=0)throw std::runtime_error("invalid video source");next[3]=q["video"];next[3]["kind"]=q["video"].value("kind",std::string(url.find("youtube.com/")!=std::string::npos||url.find("youtu.be/")!=std::string::npos?"youtube":"video"));next[3]["caption"]=q["video"].value("caption",title+" video");}
  // Same-topic updates keep prepared media and active user views; a new topic clears old content.
  for(int i=0;i<4;i++){const auto& old=tabs.last[i];bool unchanged=same_topic&&old.is_object()&&((i==0||i==2)?same_document:i==1?old.value("slides",J::array())==next[i].value("slides",J::array()):old.value("url",std::string())==next[i].value("url",std::string()));if(same_topic&&(i==1&&!q.contains("slides")||i==3&&!q.contains("video"))&&next[i].value("_empty",false)&&old.is_object()&&!old.value("_empty",false)){next[i]=old;unchanged=true;}retained[i]=unchanged&&prior_ready[i]==2;if(unchanged&&old.contains("_cache_file")){for(const char* field:{"_cache_file","_zoom","_panx","_pany","_position","page","fullscreen"})if(old.contains(field))next[i][field]=old[field];}else next[i]["_cache_file"]=cache_dir+"/context-"+std::to_string(time(nullptr))+"-"+std::to_string(getpid())+"-"+std::to_string(s->version)+"-"+media_category_name(i);tabs.last[i]=next[i];}
  s->progress.begin(title);s->progress.tabs[0]=2;for(int i=1;i<4;i++)if(retained[i])s->progress.tabs[i]=2;for(int i=1;i<4;i++)if(next[i].value("_empty",false))s->progress.tabs[i]=next[i].value("_pending",false)?0:4;s->progress.activity(incomplete?"Text ready; fetching remaining media in background":"genui.present received; PDF generated on board");s->version++;persist_tabs();bool keep_audio=tabs.active==4&&worker>0;if(!keep_audio){bool live_text=same_topic&&desired==0&&tabs.active==0&&worker>0;if(!live_text)tabs.active=-1;auto result=request({{"action","media.show"},{"params",next[desired]}},!live_text);if(!result.value("ok",false))return result;}return {{"ok",true},{"payload",{{"accepted",true},{"topic",title},{"updated_tabs",{"text","image","pdf","video"}},{"pending_media",incomplete},{"audio_preserved",true},{"generation",s->progress.generation}}}};

 }
 if(action=="media.ui"){J q=p.value("params",J::object());muse_ui::validate(q.at("document"));J params={{"kind","text"},{"ui",q["document"]},{"text",""},{"caption",q["document"].value("title",std::string("Muse"))}};return request({{"action",q.value("background",false)?"media.remember":"media.show"},{"params",params}});}
 if(action=="media.remember"){J q=p.value("params",J::object());if(q.contains("ui"))muse_ui::validate(q["ui"]);if(kind(q)!="text"||!q.contains("text")||!q["text"].is_string()||q.dump().size()>=sizeof(s->document))throw std::runtime_error("only bounded text/UI can be remembered");if(!q.contains("ui")&&tabs.last[0].is_object()&&tabs.last[0].contains("ui"))q["ui"]=tabs.last[0]["ui"];if(q.dump().size()>=sizeof(s->document))throw std::runtime_error("text/UI document too large");if(tabs.active==0&&worker>0){for(const char* field:{"_zoom","_panx","_pany","_position","_cache_file"})if(current.contains(field))q[field]=current[field];current=q;tabs.last[0]=q;publish_text(q);state("ready");}else tabs.last[0]=q;persist_tabs();return {{"ok",true}};}
 if(action=="media.switch") {J q=p.value("params",J::object());int category=media_category(q.value("kind",std::string()));if(category<0)throw std::runtime_error("tab kind must be text, image, pdf, video or audio");if(tabs.last[category].is_null()){if(category==4)return request({{"action","audio.radio"}});return request({{"action","media.show"},{"params",{{"kind",media_category_name(category)},{"caption","Muse GenUI"},{"text",std::string("Ask Muse for ")+media_category_name(category)+" content. This tab will fill when a presentation arrives."},{"_empty",true}}}},true);}if(tabs.active==category&&worker>0)return {{"ok",true},{"payload",{{"accepted",true},{"kind",media_category_name(category)},{"cached",true}}}};J saved=tabs.last[category];return request({{"action","media.show"},{"params",saved}},true);}
 if(action=="media.show") {J q=p.value("params",J::object());q.erase("_restore");if(!restore)q.erase("_empty");if(q.value("hardware",false))throw std::runtime_error("VC8000 decoding quarantined following a kernel hang; software playback is available");if(!q.is_object())throw std::runtime_error("params must be an object");std::string k=kind(q);if(k=="unknown")throw std::runtime_error("kind required for URLs without a media extension");if(k=="youtube"&&!exists(base+"youtube-resolve"))throw std::runtime_error("YouTube resolver unavailable; supply direct HTTPS video/HLS URL");if(!q.value("_empty",false)&&(k=="pdf"||k=="svg")&&!exists(base+"mutool"))throw std::runtime_error("PDF/SVG renderer unavailable");if(!q.value("_empty",false)&&(k=="video"||k=="audio"||k=="animation")&&!exists(base+"ffmpeg"))throw std::runtime_error("FFmpeg backend unavailable");if(q.dump().size()>=sizeof(s->document))throw std::runtime_error("text document too large");if(q.contains("slides")){if(k!="image")throw std::runtime_error("slides belong on image tab");muse_ui::slides_validate(q["slides"]);if(q["slides"].empty())throw std::runtime_error("slideshow requires photos");int interval=q.value("interval_seconds",1);if(interval<1||interval>60)throw std::runtime_error("slide interval must be 1..60 seconds");}if(q.contains("ui")){if(k!="text")throw std::runtime_error("UI belongs on text tab");muse_ui::validate(q["ui"]);}int category=media_category(k);if(category<0)throw std::runtime_error("unsupported media kind");int nextpage=q.value("page",1);if(nextpage<1||nextpage>10000)throw std::runtime_error("invalid page");
 if(k=="text"&&q.contains("ui")&&tabs.active==0&&worker>0&&!restore){current=q;tabs.last[0]=q;publish_text(q);persist_tabs();return {{"ok",true},{"payload",{{"accepted",true},{"kind","text"},{"live_update",true}}}};}
 if(tabs.active>=0&&!current.empty()){current["_position"]=s->position;current["_zoom"]=s->zoom;current["_panx"]=s->panx;current["_pany"]=s->pany;current["page"]=s->page;current["fullscreen"]=bool(s->full);tabs.last[tabs.active]=current;}
 stop();if(!restore){q.erase("_position");q.erase("_zoom");q.erase("_panx");q.erase("_pany");q.erase("_cache_file");q["kind"]=k;if(mkdir(cache_dir.c_str(),0700)&&errno!=EEXIST)throw std::runtime_error("cannot create tab cache");std::string path=cache_dir+"/"+media_category_name(category)+"-"+std::to_string(time(nullptr))+"-"+std::to_string(getpid())+"-"+std::to_string(s->version);unlink(path.c_str());unlink((path+".part").c_str());q["_cache_file"]=path;}
 tabs.remember(category,q);if(q.contains("slides"))s->slide_interval_seconds=q.value("interval_seconds",1);persist_tabs();s->position=q.value("_position",0.f);s->zoom=q.value("_zoom",1.f);s->panx=q.value("_panx",0.f);s->pany=q.value("_pany",0.f);s->paused=0;s->frames=0;s->decoder_pid=s->audio_pid=s->audio_decoder_pid=0;s->error[0]=0;s->audio_blocks=0;s->eq_version++;s->version++;s->full=q.value("fullscreen",false);s->page=q.value("page",1);if(s->page<1||s->page>10000)throw std::runtime_error("invalid page");current=q;if(k=="text")publish_text(q);s->selected_block=s->selected_point=-1;worker=fork();if(worker==0){play(q);_exit(0);}if(worker<0)throw std::runtime_error("cannot start media worker");setpgid(worker,worker);return {{"ok",true},{"payload",{{"accepted",true},{"kind",k}}}};}
 if(action=="media.control"){J q=p.value("params",J::object());std::string op=q.value("operation","");if(op=="slideshow_interval"){int value=q.at("value");if(value<1||value>60)throw std::runtime_error("slide interval must be 1..60 seconds");s->slide_interval_seconds=value;if(tabs.last[1].is_object())tabs.last[1]["interval_seconds"]=value;if(tabs.active==1)current["interval_seconds"]=value;persist_tabs();s->version++;return {{"ok",true},{"payload",{{"interval_seconds",value}}}};}if(op=="stop"){stop_display();return {{"ok",true}};}if(op=="pause"||op=="resume"){if(worker<=0)throw std::runtime_error("no active media");if(s->decoder_pid>0)kill(s->decoder_pid,op=="pause"?SIGSTOP:SIGCONT);if(s->audio_pid>0)kill(s->audio_pid,op=="pause"?SIGSTOP:SIGCONT);if(s->audio_decoder_pid>0)kill(s->audio_decoder_pid,op=="pause"?SIGSTOP:SIGCONT);s->paused=op=="pause";s->version++;return {{"ok",true}};}if(op=="replay"){if(current.empty())throw std::runtime_error("no previous media");return request({{"action","media.show"},{"params",current}});}if(op=="volume"||op=="mute"){if(op=="volume")s->volume=std::clamp(q.value("value",75),0,100);else s->muted=q.value("enabled",!bool(s->muted));waitok(spawn({"/usr/bin/amixer","-q","sset","Headphone",std::to_string(s->volume)+"%",s->muted?"mute":"unmute"}));}else if(op=="temperature")s->temperature=std::clamp(q.value("value",72),50,90);else if(op=="dsp"){dsp_control(q.value("feature",std::string()),q.value("enabled",true));}else if(op=="hardware_equalizer"){double gain=q.value("value",0.0);if(!std::isfinite(gain)||gain<-12||gain>12)throw std::runtime_error("hardware gain must be -12..12 dB");hw_adjust(q.value("band",-1),int(std::lround(gain)));}else if(op=="eq_default"){eq_default();}else if(op=="equalizer"){int band=q.value("band",-1);double gain=q.value("value",0.0);if(band<0||band>=10||!std::isfinite(gain)||gain<-12||gain>12)throw std::runtime_error("EQ band must be 0..9 and gain -12..12 dB");eq_write(&s->eq_gain[band],int(std::lround(gain*10)));s->eq_version++;}else if(op=="eq_flat"){for(auto& gain:s->eq_gain)eq_write(&gain,0);s->eq_version++;}else if(op=="eq_view"){int view=q.value("value",q.value("enabled",true)?1:0);if(view<0||view>3)throw std::runtime_error("view must be 0..3");s->eq_view=view;}else if(op=="fullscreen")s->full=q.value("enabled",!bool(s->full));else if(op=="zoom"){float value=q.value("value",1.f);if(!std::isfinite(value)||value<1||value>4)throw std::runtime_error("zoom must be 1..4");s->zoom=value;}else if(op=="pan"){s->panx=std::clamp(q.value("x",0.f),-8192.f,8192.f);s->pany=std::clamp(q.value("y",0.f),-8192.f,8192.f);}else if(op=="page"){int value=q.value("value",1);if(value<1||value>10000)throw std::runtime_error("invalid page");s->page=value;}else if(op=="fit"){s->zoom=1;s->panx=s->pany=0;}else throw std::runtime_error("unknown media operation");s->version++;return {{"ok",true}};}
 throw std::runtime_error("unknown action");}
static bool ui_select(int x,int y){
 if(!current.contains("ui"))return false;const auto& doc=current["ui"];float z=s->zoom;int left=(s->full?0:24)+int(s->panx),top=(s->full?0:124)+int(s->pany),width=int(((s->full?1024:650)-24)*z);
 top+=int(muse_ui::header_height(doc)*z);
 int index=0;for(const auto& b:doc["blocks"]){int height=int(muse_ui::block_height(b)*z);auto type=b.value("type",std::string());if((type=="bar"||type=="line")&&y>=top+int(50*z)&&y<=top+int(214*z)){int px=left+int(68*z),pw=width-int(100*z),count=b["labels"].size();if(x>=px&&x<px+pw){s->selected_block=index;s->selected_point=std::clamp((x-px)*count/pw,0,count-1);s->version++;return true;}}top+=height+int(12*z);index++;}return false;
}
static void touch(int x,int y,int dx,int dy,bool release,bool drag,double duration){

 if(release&&s->progress.visible&&x>=598&&x<650&&y>=176&&y<224){s->progress.visible=0;s->version++;return;}
 if(s->progress.visible&&x>=52&&x<646&&y>=176&&y<472)return;
 if(release&&!drag&&!s->full&&kind(current)=="audio"&&x>=40&&x<650&&y>=235&&y<415){int station=(y-235)/60;if(station<3){try{request({{"action","audio.radio"},{"params",{{"station",radio_stations[station].id}}}});}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}return;}}
 if(!release){if((x>=24&&x<674&&y>=124&&y<504)||s->full){s->panx+=dx;s->pany+=dy;s->version++;}return;}
 if(drag||duration>.8)return;
 if(!s->full&&y>=56&&y<140&&(y<120||x<688)){int category=(x-24)/196;if(x>=24&&x<1004&&category>=0&&category<5){try{request({{"action","media.switch"},{"params",{{"kind",media_category_name(category)}}}});}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}}return;}
 if(s->full&&x>=820&&y<120)s->full=0;
 else if(!s->full&&x>=704){
  if(y>=100&&y<166)s->eq_view=std::clamp((x-704)/74,0,3);
  if(s->eq_view==3&&y>=170&&y<446){int row=(y-170)/46;const char* features[]={"software_eq","hardware_eq","limiter","mic_hpf","mic_alc","mic_gate"};int flags[]={s->sw_eq,s->hw_eq,s->limiter,s->mic_hpf,s->mic_alc,s->mic_gate};try{dsp_control(features[row],!flags[row]);}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}}
  if(s->eq_view==3&&y>=453&&y<500)eq_default();
  if(s->eq_view==2&&y>=441&&y<490){if(x<850)codec_eq(!s->hw_eq);else eq_default();}
  if(!s->eq_view&&y>=411&&y<=461){if(x<800)s->temperature=std::max(50,s->temperature-1);else if(x>900)s->temperature=std::min(90,s->temperature+1);}
  if(y>=505){if(x<790){s->volume=std::max(0,s->volume-5);s->muted=0;}else if(x>912){s->volume=std::min(100,s->volume+5);s->muted=0;}else s->muted=!s->muted;try{waitok(spawn({"/usr/bin/amixer","-q","sset","Headphone",std::to_string(s->volume)+"%",s->muted?"mute":"unmute"}));}catch(...){} }
 }else if(!s->full&&x>=24&&x<674&&y>=524){
  bool video=kind(current)=="video"||kind(current)=="youtube"||kind(current)=="animation"||kind(current)=="audio";
  if(x<122){if(video&&(!strcmp(s->state,"ended")||!strcmp(s->state,"stopped"))){request({{"action","media.show"},{"params",current}});}else if(video&&worker>0){s->paused=!s->paused;if(s->decoder_pid>0)kill(s->decoder_pid,s->paused?SIGSTOP:SIGCONT);if(s->audio_pid>0)kill(s->audio_pid,s->paused?SIGSTOP:SIGCONT);if(s->audio_decoder_pid>0)kill(s->audio_decoder_pid,s->paused?SIGSTOP:SIGCONT);}else{s->zoom=1;s->panx=s->pany=0;}}
  else if(kind(current)=="text"&&x>=304&&x<422){try{request({{"action","media.speech"},{"params",{{"operation","read"}}}});}catch(const std::exception&e){s->speech_phase=3;snprintf(s->speech_error,sizeof(s->speech_error),"%s",e.what());}}
  else if(kind(current)=="text"&&x>=588){request({{"action","media.speech"},{"params",{{"operation","stop"}}}});}
  else if(x<212)s->zoom=std::max(1.f,s->zoom-.5f);
  else if(x<302)s->zoom=std::min(4.f,s->zoom+.5f);else if(x<422&&video){eq_default();}else if(x<362&&!video)s->page=std::max(1,s->page-1);else if(x<422&&!video)s->page=std::min(10000,s->page+1);
  else if(x<588)s->full=1;
  else stop_display();
 }else if((x>=24&&x<674&&y>=124&&y<504)||s->full){if(ui_select(x,y))return;}
 s->version++;
}
static J touch_target(int startx,int starty,int x,int y,bool dragged,bool full){bool button=(s->progress.visible&&startx>=598&&startx<650&&starty>=176&&starty<224)||(full&&startx>=820&&starty<120)||(!full&&starty>=56&&starty<140&&(starty<120||startx<688)&&startx>=24&&startx<1004)||(!full&&kind(current)=="audio"&&startx>=40&&startx<650&&starty>=235&&starty<415)||(!full&&(startx>=704||(startx>=24&&startx<674&&starty>=524)));return {{"x",button?startx:x},{"y",button?starty:y},{"drag",button?false:dragged},{"button",button}};}
static int prepare_context(int generation){auto update=[&](int i,int state,const std::string& detail){return muse_board::call("media.progress",{{"operation","update"},{"generation",generation},{"index",i},{"state",state},{"detail",detail}}).value("ok",false);};auto activity=[&](const std::string& detail){if(!muse_board::call("media.progress",{{"operation","activity"},{"generation",generation},{"detail",detail}}).value("ok",false))throw std::runtime_error("Presentation replaced");};if(!update(0,2,"Text document validated"))return 0;setpriority(PRIO_PROCESS,0,15);
 for(int i:{2,1,3}){auto ready=muse_board::call("media.progress",{{"operation","status"}});if(ready["payload"]["generation"]!=generation)return 0;if(ready["payload"]["tabs"][i]["state"]=="ready")continue;auto p=tabs.last[i];if(!p.is_object()||p.value("_empty",false)){if(!update(i,p.value("_pending",false)?0:4,p.value("_pending",false)?"Waiting for remaining media URLs from Muse":"No source supplied for this tab"))return 0;continue;}if(!update(i,1,std::string("Preparing ")+media_category_name(i)))return 0;
 try{std::string cache=p.at("_cache_file"),source=p.value("url",std::string());if(i==1||i==2){int count=i==1&&p.contains("slides")?int(p["slides"].size()):1;for(int page=1;page<=count;page++){std::string target=cache;if(i==1&&p.contains("slides")){source=p["slides"][page-1].at("url");target+="-"+std::to_string(page);}std::string raw=target+(i==1?".rgb":".page-1.rgb");muse_media::RasterCache pixels;if(!pixels.open(raw)){activity(i==1?"Downloading image "+std::to_string(page)+"/"+std::to_string(count):"Rendering generated PDF page 1");std::string path=(i==1?image_input(source,target,generation):fetch(source,target,8388608,generation)),raster=path;if(i==2){raster="/tmp/muse-media-prepare-"+std::to_string(getpid())+".png";waitok(spawn({base+"mutool","draw","-q","-F","png","-w","1400","-h","1400","-o",raster,path,"1"}));}int w,h,n;if(!stbi_info(raster.c_str(),&w,&h,&n)||w>4096||h>4096||int64_t(w)*h>4000000)throw std::runtime_error("Image too large or unsupported");auto data=stbi_load(raster.c_str(),&w,&h,&n,3);if(!data)throw std::runtime_error("Image decoding failed");muse_media::RasterCache::write(raw,w,h,data);stbi_image_free(data);}activity(i==1?"Image "+std::to_string(page)+"/"+std::to_string(count)+" decoded and cached":"PDF page 1 decoded and cached");}}
 else{std::string input=source;if(access(cache.c_str(),R_OK)==0)input=cache;else{if(kind(p)=="youtube"){activity("Resolving YouTube public stream");input=youtube_source(source,cache);}activity("Preparing video: download small file or stream large file");if(!p.value("stream",false))input=video_input(input,cache,generation);if(input.rfind("https://",0)==0)activity("Streaming video; checking first decoded frame");else activity("Video cached; checking first decoded frame");}
 std::vector<std::string> args={base+"ffmpeg","-nostdin","-v","error","-threads","1","-filter_threads","1","-rw_timeout","15000000"};if(input.rfind("https://",0)==0)args.insert(args.end(),{"-tls_verify","1","-ca_file",base+"ca-certificates.crt"});std::string preview="/tmp/muse-prepare-video-"+std::to_string(getpid());int fd=open(preview.c_str(),O_CREAT|O_TRUNC|O_RDWR,0600);args.insert(args.end(),{"-i",input,"-an","-frames:v","1","-vf","scale=1:1","-pix_fmt","rgb24","-f","rawvideo","pipe:1"});waitok(spawn(args,-1,fd));close(fd);auto decoded=readfile(preview,16);unlink(preview.c_str());if(decoded.size()!=3)throw std::runtime_error("No video frame decoded");}
 if(!update(i,2,std::string(media_category_name(i))+" ready: source decoded successfully"))return 0;
 }catch(const std::exception& e){if(!update(i,3,std::string(media_category_name(i))+": "+e.what()))return 0;}}
 return 0;
}

int main(int argc,char**argv){signal(SIGPIPE,SIG_IGN);signal(SIGTERM,[](int){exiting=1;});signal(SIGINT,[](int){exiting=1;});s=(Shared*)mmap(nullptr,sizeof(Shared),PROT_READ|PROT_WRITE,MAP_SHARED|MAP_ANONYMOUS,-1,0);new(s)Shared();if(mkdir(cache_dir.c_str(),0700)&&errno!=EEXIST){perror("tab cache");return 1;}try{J index=J::parse(readfile(cache_dir+"/tabs.json",1048576));if(index.is_array()&&index.size()==5)for(int i=0;i<5;i++)if(index[i].is_object())tabs.last[i]=index[i];}catch(...){}if(argc>2&&std::string(argv[1])=="--prepare"){try{signal(SIGTERM,SIG_DFL);return prepare_context(std::stoi(argv[2]));}catch(const std::exception&e){std::cerr<<e.what();return 1;}}if(argc>1&&std::string(argv[1])=="--touch-target"){J q=J::parse(argv[2]);std::cout<<touch_target(q["start_x"],q["start_y"],q["x"],q["y"],q.value("drag",false),q.value("fullscreen",false)).dump()<<"\n";return 0;}if(argc>1&&std::string(argv[1])=="--video-input"){try{auto q=J::parse(argv[2]);std::cout<<video_input(q.at("url"),q.at("cache"));return 0;}catch(const std::exception&e){std::cerr<<e.what();return 1;}}if(argc>1&&std::string(argv[1])=="--image-source"){std::cout<<muse_media::image_source(argv[2]);return 0;}if(argc>1&&std::string(argv[1])=="--classify"){std::cout<<kind(J::parse(argv[2]))<<"\n";return 0;}if(argc>1&&std::string(argv[1])=="--batch"){J out=J::array();for(auto p:J::parse(argv[2])){try{out.push_back(request(p));}catch(const std::exception&e){out.push_back({{"ok",false},{"error",e.what()}});}}std::cout<<out.dump()<<"\n";stop();return 0;}if(argc>1&&std::string(argv[1])=="--request"){try{std::cout<<request(J::parse(argv[2])).dump()<<"\n";}catch(const std::exception&e){std::cout<<J({{"ok",false},{"error",e.what()}}).dump()<<"\n";}stop();return 0;}if(argc>1)fbpath=argv[1];
 preload_brand_assets();
 muse_audio::Codec device;codec=&device;if(device.available()){try{auto gains=device.gains();s->codec_available=1;for(int i=0;i<5;i++){s->hw_gain[i]=gains[i];if(gains[i])s->hw_eq=1;}s->limiter=device.get("DAC Limiter Switch");s->mic_hpf=device.get("High Pass Filter Switch");s->mic_alc=bool(device.get("ALC Enable Switch",true));s->mic_gate=device.get("ALC Noise Gate Switch");}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}}
 int server=socket(AF_INET,SOCK_STREAM|SOCK_CLOEXEC,0);int yes=1;setsockopt(server,SOL_SOCKET,SO_REUSEADDR,&yes,sizeof(yes));sockaddr_in a{};a.sin_family=AF_INET;a.sin_port=htons(8765);a.sin_addr.s_addr=htonl(INADDR_LOOPBACK);if(bind(server,(sockaddr*)&a,sizeof(a))||listen(server,8)){perror("listen");return 1;}
 int input=open("/dev/input/event0",O_RDONLY|O_NONBLOCK);input_absinfo ax{},ay{};if(input>=0){ioctl(input,EVIOCGABS(ABS_X),&ax);ioctl(input,EVIOCGABS(ABS_Y),&ay);}int rx=0,ry=0,down=0,last=0,px=0,py=0,startx=0,starty=0,slider=-1;bool dragged=false;double started=0;
 while(!exiting){static int last_elapsed=-1;int elapsed=s->progress.started>0?int(now()-s->progress.started):0;if(s->progress.visible&&elapsed!=last_elapsed){last_elapsed=elapsed;s->version++;}if(s->progress.visible&&s->progress.hide_at>0&&now()>s->progress.hide_at){s->progress.visible=0;s->version++;}pollfd fds[2]={{server,POLLIN,0},{input,POLLIN,0}};poll(fds,2,100);int child_status=0;if(worker>0&&waitpid(worker,&child_status,WNOHANG)==worker){kill(-worker,SIGTERM);worker=0;s->decoder_pid=s->audio_pid=s->audio_decoder_pid=0;eq_write(&s->audio_running,0);if(strcmp(s->state,"error")&&strcmp(s->state,"ended")){snprintf(s->error,sizeof(s->error),"media worker exited unexpectedly (status %d)",child_status);state("error");}unlink("/tmp/muse-native-media.active");if(!strcmp(s->state,"ended")&&!pending.empty()){J next=pending.front();pending.pop_front();try{request({{"action","media.show"},{"params",next}});}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());state("error");}}}if(worker>0&&!strcmp(s->state,"ended")&&!pending.empty()){J next=pending.front();pending.pop_front();try{request({{"action","media.show"},{"params",next}});}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());state("error");}}if(fds[1].revents&POLLIN){input_event e{};while(read(input,&e,sizeof(e))==sizeof(e)){if(e.type==EV_ABS&&e.code==ABS_X)rx=e.value;if(e.type==EV_ABS&&e.code==ABS_Y)ry=e.value;if(e.type==EV_KEY&&e.code==BTN_TOUCH)down=e.value;if(e.type==EV_SYN&&e.code==SYN_REPORT){int x=(rx-ax.minimum)*1023/std::max(1,ax.maximum-ax.minimum),y=599-(ry-ay.minimum)*599/std::max(1,ay.maximum-ay.minimum);if(down&&!last){startx=px=x;starty=py=y;started=now();dragged=false;slider=eq_band(x,y);int hw=hw_band(x,y);if(hw>=0)slider=10+hw;if(slider>=10){try{hw_slider(slider-10,y);}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}}else if(slider>=0)eq_adjust(slider,y);}else if(down&&last){if(slider>=10){try{hw_slider(slider-10,y);}catch(const std::exception&e){snprintf(s->error,sizeof(s->error),"%s",e.what());}}else if(slider>=0)eq_adjust(slider,y);if(abs(x-startx)+abs(y-starty)>10)dragged=true;if(dragged&&startx<674&&starty>=140&&starty<504)touch(x,y,x-px,y-py,false,true,0);}else if(!down&&last&&slider<0){J target=touch_target(startx,starty,x,y,dragged,s->full);bool button=target["button"];fprintf(stderr,"touch %d,%d release %d,%d drag=%d button=%d\n",startx,starty,x,y,dragged,button);touch(target["x"],target["y"],0,0,true,target["drag"],button?0:now()-started);}px=x;py=y;last=down;}}}
 if(fds[0].revents&POLLIN){int c=accept4(server,nullptr,nullptr,SOCK_CLOEXEC);timeval timeout{2,0};setsockopt(c,SOL_SOCKET,SO_RCVTIMEO,&timeout,sizeof(timeout));std::string data;char buf[4096];J out;try{size_t header=std::string::npos,length=0;while(data.size()<280000){ssize_t n=read(c,buf,sizeof(buf));if(n<=0)throw std::runtime_error("incomplete HTTP request");data.append(buf,n);header=data.find("\r\n\r\n");if(header!=std::string::npos){auto lower=data.substr(0,header);std::transform(lower.begin(),lower.end(),lower.begin(),::tolower);auto pos=lower.find("content-length:");if(pos==std::string::npos)throw std::runtime_error("Content-Length required");length=std::stoul(lower.substr(pos+15));if(length>262144)throw std::runtime_error("request too large");if(data.size()>=header+4+length)break;}}if(header==std::string::npos||data.rfind("POST /media ",0)!=0)throw std::runtime_error("use POST /media");out=request(J::parse(data.substr(header+4,length)));}catch(const std::exception&e){out={{"ok",false},{"error",e.what()}};}std::string body=out.dump();std::string response="HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nConnection: close\r\nContent-Length: "+std::to_string(body.size())+"\r\n\r\n"+body;size_t done=0;while(done<response.size()){ssize_t n=write(c,response.data()+done,response.size()-done);if(n<=0)break;done+=n;}close(c);}}
 stop();close(server);if(input>=0)close(input);
}
