// SPDX-License-Identifier: Apache-2.0
// Bounded board-side discovery. No laptop proxy or cloud agent search dependency.
#include "quick_sources.hpp"
#include "board_media_client.hpp"
#include <fstream>
#include <iostream>
#include <chrono>
#include <sys/un.h>
#include <sys/wait.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <signal.h>
using J=nlohmann::json;
static std::string base="/mnt/sd/muse/media/",tmp;
struct Fetch{pid_t pid;std::string path;};
static Fetch fetch(const std::string& url,int id){std::string path=tmp+"/"+std::to_string(id);pid_t p=fork();if(p==0){int fd=open((path+".err").c_str(),O_CREAT|O_TRUNC|O_WRONLY,0600);dup2(fd,2);for(int i=3;i<1024;i++)close(i);execl((base+"curl").c_str(),"curl","--fail","--location","--silent","--show-error","--proto","=https","--proto-redir","=https","--max-time","8","--max-filesize","4194304","--cacert",(base+"ca-certificates.crt").c_str(),"-o",path.c_str(),url.c_str(),nullptr);_exit(127);}if(p<0)throw std::runtime_error("Cannot start source fetch");return {p,path};}
static std::string collect(Fetch f){int status;while(waitpid(f.pid,&status,0)<0)if(errno!=EINTR)throw std::runtime_error("Cannot collect source fetch");std::ifstream in(f.path);std::string s((std::istreambuf_iterator<char>(in)),{});unlink(f.path.c_str());unlink((f.path+".err").c_str());if(!WIFEXITED(status)||WEXITSTATUS(status)!=0||s.empty())throw std::runtime_error("Source unavailable within 8 seconds");return s;}
static J present(const J& params){int fd=socket(AF_UNIX,SOCK_STREAM|SOCK_CLOEXEC,0);sockaddr_un a{};a.sun_family=AF_UNIX;strcpy(a.sun_path,"/run/musegadget.sock");if(fd<0||connect(fd,(sockaddr*)&a,sizeof(a)))throw std::runtime_error("Gateway unavailable");timeval t{10,0};setsockopt(fd,SOL_SOCKET,SO_RCVTIMEO,&t,sizeof(t));std::string q=J({{"action","genui.present"},{"params",params}}).dump()+"\n";size_t at=0;while(at<q.size()){auto n=write(fd,q.data()+at,q.size()-at);if(n<=0)throw std::runtime_error("Gateway send failed");at+=n;}std::string out;char b[4096];ssize_t n;while((n=read(fd,b,sizeof(b)))>0)out.append(b,n);close(fd);auto r=J::parse(out);if(!r.value("ok",false))throw std::runtime_error(r.value("error",std::string("Presentation failed")));return r;}
int main(int argc,char**argv){signal(SIGPIPE,SIG_IGN);try{if(argc==3&&std::string(argv[1])=="--parse-youtube"){std::ifstream f(argv[2]);std::string s((std::istreambuf_iterator<char>(f)),{});std::cout<<muse_quick::video(muse_quick::youtube_data(s)).dump();return 0;}if(argc<2)return 2;std::string title=muse_quick::article(muse_quick::topic(argv[1]));tmp="/tmp/muse-discovery-"+std::to_string(getpid());mkdir(tmp.c_str(),0700);auto start=std::chrono::steady_clock::now();auto activity=[](std::string s){muse_board::call("media.progress",{{"operation","activity"},{"detail",s}});};activity("Board fetching summary, photo list and YouTube in parallel");auto summary=fetch("https://en.wikipedia.org/api/rest_v1/page/summary/"+muse_quick::encode(title),0),photos=fetch("https://en.wikipedia.org/api/rest_v1/page/media-list/"+muse_quick::encode(title),1),youtube=fetch("https://www.youtube.com/results?search_query="+muse_quick::encode(title),2);J doc=muse_quick::document(J::parse(collect(summary)));J params={{"_board_request",argc>2?argv[2]:""},{"version","1"},{"document",doc},{"pending_media",true},{"prepare_seconds",55}};present(params);activity("Text ready; collecting photo URLs and YouTube result");std::string photo_error,video_error;try{params["slides"]=muse_quick::slides(J::parse(collect(photos)),doc["title"],doc["sources"][0]["url"]);if(params["slides"].size()<10)photo_error="Article provides fewer than 10 usable photos";}catch(const std::exception& e){photo_error=e.what();}try{auto v=muse_quick::video(muse_quick::youtube_data(collect(youtube)));if(v.is_null())throw std::runtime_error("No public YouTube video in search results");params["video"]=v;}catch(const std::exception& e){video_error=e.what();}params["pending_media"]=false;int elapsed=std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now()-start).count();params["prepare_seconds"]=std::max(1,59-elapsed);auto r=present(params);int generation=r["payload"]["generation"];for(auto failure:{std::make_pair(1,photo_error),std::make_pair(3,video_error)})if(!failure.second.empty())muse_board::call("media.progress",{{"operation","activity"},{"generation",generation},{"detail",failure.second}});rmdir(tmp.c_str());std::cerr<<"Direct discovery published "<<doc["title"]<<" in "<<elapsed<<" seconds\n";return 0;}catch(const std::exception&e){try{auto r=muse_board::call("media.progress",{{"operation","status"}});muse_board::call("media.progress",{{"operation","update"},{"generation",r["payload"]["generation"]},{"index",0},{"state",3},{"detail",std::string("Direct discovery: ")+e.what()}});}catch(...){}std::cerr<<e.what()<<"\n";return 1;}}
