// SPDX-License-Identifier: Apache-2.0
#pragma once
#include "generative_ui.hpp"
#include <algorithm>
#include <cstring>
#include <cctype>
#include <set>
namespace muse_quick {
using J=nlohmann::json;
inline std::string encode(const std::string& s){std::string r;const char* h="0123456789ABCDEF";for(unsigned char c:s){if(std::isalnum(c)||c=='-'||c=='_'||c=='.'||c=='~')r+=c;else{r+='%';r+=h[c>>4];r+=h[c&15];}}return r;}
inline std::string topic(std::string s){std::string lower=s;std::transform(lower.begin(),lower.end(),lower.begin(),[](unsigned char c){return std::tolower(c);});for(const char* p:{"show me stuff on ","show me stuff about ","i wanna see stuff on ","show me ","latest news on ","news on "}){auto at=lower.find(p);if(at!=std::string::npos){s=s.substr(at+strlen(p));break;}}while(!s.empty()&&(std::isspace((unsigned char)s.front())||s.front()=='\''||s.front()=='"'))s.erase(s.begin());while(!s.empty()&&(std::isspace((unsigned char)s.back())||s.back()=='\''||s.back()=='"'||s.back()=='?'||s.back()=='.'))s.pop_back();if(s.rfind("the ",0)==0)s.erase(0,4);if(s.empty()||s.size()>140)throw std::runtime_error("Topic must contain 1..140 characters");return s;}
inline std::string article(std::string s){std::string l=s;std::transform(l.begin(),l.end(),l.begin(),[](unsigned char c){return std::tolower(c);});if(l=="usa"||l=="us"||l=="united states")return "United States";if(l=="meta")return "Meta Platforms";if(l=="yankees")return "New York Yankees";if(l=="a's"||l=="oakland a's")return "Oakland Athletics";if(l=="taiwan")return "Taiwan";if(!s.empty())s[0]=std::toupper((unsigned char)s[0]);return s;}
inline J slides(const J& media,const std::string& title,const std::string& source){J result=J::array();std::set<std::string> used;for(const auto& item:media.value("items",J::array())){std::string name=item.value("title",std::string()),l=name;std::transform(l.begin(),l.end(),l.begin(),[](unsigned char c){return std::tolower(c);});if(item.value("type",std::string())!="image"||!item.value("showInGallery",false)||!(l.size()>4&&(l.substr(l.size()-4)==".jpg"||l.substr(l.size()-5)==".jpeg"))||!item.contains("srcset")||item["srcset"].empty())continue;std::string url=item["srcset"][0].value("src",std::string());if(url.rfind("//",0)==0)url="https:"+url;auto q=url.find('?');if(q!=std::string::npos)url.resize(q);if(url.rfind("https://thumb.wikimedia.org/wikipedia/commons/",0)!=0&&url.rfind("https://upload.wikimedia.org/wikipedia/commons/",0)!=0)continue;if(!used.insert(url).second)continue;result.push_back({{"url",url},{"caption",title+" photo "+std::to_string(result.size()+1)},{"source",source}});if(result.size()==10)break;}return result;}
inline J youtube_data(const std::string& html){auto at=html.find("ytInitialData = ");if(at==std::string::npos)at=html.find("ytInitialData=");if(at==std::string::npos)throw std::runtime_error("YouTube search data unavailable");at=html.find('{',at);if(at==std::string::npos)throw std::runtime_error("Invalid YouTube search data");bool quote=false,escape=false;int depth=0;for(size_t i=at;i<html.size();i++){char c=html[i];if(quote){if(escape)escape=false;else if(c=='\\')escape=true;else if(c=='"')quote=false;}else if(c=='"')quote=true;else if(c=='{')depth++;else if(c=='}'&&--depth==0)return J::parse(html.substr(at,i-at+1));}throw std::runtime_error("Truncated YouTube search data");}
inline J video(const J& tree){if(tree.is_object()){if(tree.contains("videoRenderer")){const auto& r=tree["videoRenderer"];auto id=r.value("videoId",std::string());if(id.size()==11&&r.contains("lengthText")){std::string title="YouTube video";if(r.contains("title")&&r["title"].contains("runs")&&!r["title"]["runs"].empty())title=r["title"]["runs"][0].value("text",title);return {{"kind","youtube"},{"url","https://www.youtube.com/watch?v="+id},{"caption",title.substr(0,180)},{"stream",true}};}}for(const auto& child:tree){auto v=video(child);if(!v.is_null())return v;}}else if(tree.is_array())for(const auto& child:tree){auto v=video(child);if(!v.is_null())return v;}return nullptr;}
inline J document(const J& summary){std::string title=summary.at("title"),source=summary.at("content_urls").at("desktop").at("page");J doc={{"title",title},{"theme","vivid"},{"subtitle",summary.value("description",std::string("Topic overview"))},{"source","Wikipedia overview; retrieved now. Media from article sources."},{"sources",J::array({{{"title",title+" - Wikipedia"},{"url",source}}})},{"blocks",J::array({{{"type","text"},{"title","Overview"},{"text",summary.at("extract").get<std::string>().substr(0,4096)}}})}};if(summary.contains("coordinates"))doc["blocks"].push_back({{"type","metrics"},{"items",J::array({{{"title","Latitude"},{"value",summary["coordinates"]["lat"]}},{{"title","Longitude"},{"value",summary["coordinates"]["lon"]}}})}});if(summary.contains("timestamp"))doc["blocks"].push_back({{"type","text"},{"title","Source freshness"},{"text","Article last updated: "+summary["timestamp"].get<std::string>()+". Overview photos may include historical views; this is not a live news or statistics feed."}});muse_ui::validate(doc);return doc;}
}
