// SPDX-License-Identifier: Apache-2.0
// Native resolver for directly exposed public YouTube streams. No laptop/runtime Python.
#include "vendor/json.hpp"
#include <unistd.h>
#include <sys/wait.h>
#include <fstream>
#include <iostream>
#include <regex>
using J=nlohmann::json;
int main(int argc,char**argv){try{if(argc!=2)throw std::runtime_error("YouTube URL required");std::string url=argv[1],id;std::smatch m;std::regex pattern(R"(^https://(?:www\.|m\.)?(?:youtu\.be/|youtube\.com/(?:watch\?[^#]*v=|shorts/|embed/))([A-Za-z0-9_-]{11})(?:[?&#/].*)?$)");if(!std::regex_match(url,m,pattern))throw std::runtime_error("invalid YouTube video URL");id=m[1];url="https://www.youtube.com/watch?v="+id;pid_t child=fork();if(!child){execl("/opt/muse-media/curl","curl","--fail","--location","--silent","--show-error","--proto","=https","--proto-redir","=https","--max-time","30","--max-filesize","8388608","--cacert","/opt/muse-media/ca-certificates.crt","-A","Mozilla/5.0","-o","/tmp/muse-youtube.html",url.c_str(),(char*)nullptr);_exit(127);}int status;waitpid(child,&status,0);if(!WIFEXITED(status)||WEXITSTATUS(status))throw std::runtime_error("YouTube HTTPS request failed");std::ifstream file("/tmp/muse-youtube.html");std::string html((std::istreambuf_iterator<char>(file)),{});if(html.size()>8388608)throw std::runtime_error("YouTube response too large");size_t start=html.find("ytInitialPlayerResponse =");if(start==std::string::npos)throw std::runtime_error("YouTube player metadata unavailable");start=html.find('{',start);bool quoted=false,escape=false;int depth=0;size_t end=start;for(;end<html.size();end++){char c=html[end];if(quoted){if(escape)escape=false;else if(c=='\\')escape=true;else if(c=='"')quoted=false;}else{if(c=='"')quoted=true;else if(c=='{')depth++;else if(c=='}'&&!--depth){end++;break;}}}J player=J::parse(html.substr(start,end-start));auto streams=player.value("streamingData",J::object());std::string selected;int best=100000;for(auto f:streams.value("formats",J::array())){int h=f.value("height",10000);if(f.contains("url")&&f.value("mimeType",std::string()).find("video/mp4")!=std::string::npos&&h<best){selected=f["url"];best=h;}}if(selected.empty())selected=streams.value("hlsManifestUrl",std::string());if(selected.empty()){
 J payload={{"videoId",id},{"context",{{"client",{{"clientName","ANDROID"},{"clientVersion","20.10.38"},{"hl","en"},{"gl","US"}}},{"thirdParty",{{"embedUrl","https://www.youtube.com/"}}}}},{"contentCheckOk",true},{"racyCheckOk",true}};
 {std::ofstream out("/tmp/muse-youtube-request.json");out<<payload.dump();}
 child=fork();if(!child){execl("/opt/muse-media/curl","curl","--fail","--silent","--show-error","--max-time","20","--cacert","/opt/muse-media/ca-certificates.crt","-H","Content-Type: application/json","--data-binary","@/tmp/muse-youtube-request.json","-o","/tmp/muse-youtube-player.json","https://www.youtube.com/youtubei/v1/player",(char*)nullptr);_exit(127);}waitpid(child,&status,0);
 if(WIFEXITED(status)&&!WEXITSTATUS(status)){std::ifstream f("/tmp/muse-youtube-player.json");J reply;f>>reply;auto data=reply.value("streamingData",J::object());for(auto format:data.value("formats",J::array())){int h=format.value("height",10000);if(format.contains("url")&&format.value("mimeType",std::string()).find("video/mp4")!=std::string::npos&&h<best){selected=format["url"];best=h;}}if(selected.empty())selected=data.value("hlsManifestUrl",std::string());}
 }
 if(selected.rfind("https://",0)!=0)throw std::runtime_error("YouTube requires a signed/JavaScript player or sign-in; direct public stream unavailable");std::cout<<selected<<"\n";return 0;}catch(const std::exception&e){std::cerr<<e.what()<<"\n";return 1;}}
